UPSERT: Fix erroneous reporting of effects
Comdb2 could report incorrect query effects when multiple transactions
are executed in parallel. This happens when a transaction gets replayed
on the master.

Fixed by resetting effects object, stored in the ireq snapshot, before
every transaction replay.

Amitava Bhattacharyya <abhattachar9@bloomberg.net> reported this bug
and also contributed the included test cases.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

diff --git a/tests/upsert.test/runit b/tests/upsert.test/runit
--- a/tests/upsert.test/runit
+++ b/tests/upsert.test/runit
@@ -97,5 +97,15 @@ for showeffectsfile in $showeffectsfiles; do
     verify $testname
 done
 
+# 5) Bug: Query effects when multiple transactions are executing in parallel
+./upsert_effects.sh ${CDB2_OPTIONS} $dbname > upsert_effects.output
+if [[  $? -eq 0 ]]; then
+    echo "passed upsert_effects.sh"
+else
+    echo "failed upsert_effects.sh"
+    cat upsert_effects.output
+    exit 1
+fi
+
 echo "Testcase passed."
 exit 0
