Autofill a column entries with guid() at insertion time (#2371)
This feature is similar to autoincrement, except that the value assigned is a guid (which is stored as byte[16]).
To have an autoasigned guid column, create table with a byte[16] field with dbstore set to "GUID" or "UUID",
like the following schema:

```
schema
{
    byte   auto_guid[16] dbstore="GUID"
    int    i
}
```
Or with DDL:
```
> cdb2sql adidb 'create table t1(auto_guid byte(16) DEFAULT GUID, i int)'
> cdb2sql adidb 'insert into t1(i) values(1),(2)'
> cdb2sql adidb 'select guid_str(auto_guid) as str, * from t1'
(str='9341d907-c843-4ec6-844f-2a461379c3e1', auto_guid=x'9341d907c8434ec6844f2a461379c3e1', i=1)
(str='ed21148a-85af-4368-ae46-0787f900ee6e', auto_guid=x'ed21148a85af4368ae460787f900ee6e', i=2)
```

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

diff --git a/tests/guid.test/runit b/tests/guid.test/runit
--- a/tests/guid.test/runit
+++ b/tests/guid.test/runit
@@ -36,7 +36,7 @@ for ((i=1;i<=$CNT;i++)) ; do
     echo "insert into t1 values(guid(), randomblob(16), $i,$((2*i)))"
 done >> ins.in
 
-echo 'using cte for kicks and gigles'
+echo 'using cte for speed'
 echo "INSERT INTO t1 (id,rndm,i,j) WITH tblx(x) AS ( VALUES(1) UNION ALL SELECT x+1 FROM tblx where x < $CNT) SELECT guid(), randomblob(16), x,($CNT-x) FROM tblx" >> ins.in
 
 
@@ -90,6 +90,100 @@ fi
 mult=`grep "^count" sel2.out | grep -v "=1" | wc -l`
 echo "found $mult with duplicate key for randomblob()"
 
+
+echo "Testing having guid as autoassigned colun via dbstore"
+
+# if line is 'byte        auto_guid[17] dbstore="UUID"' it should fail with syntax error:
+#} }] failed with rc 240 Error at line   3: CAN ONLY HAVE BYTE[16] FOR GUID DBSTORE: auto_guid
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2 { 
+schema 
+{
+    byte auto_guid[16] dbstore="UUID"
+    int  i
+}
+}'
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'insert into t2(i) values(1)'
+assertcnt t2 1
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t2'
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2(auto_guid byte(16) DEFAULT UUID, i int)'
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'insert into t2(i) values(1)'
+assertcnt t2 1
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t2'
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2(auto_guid byte(16) DEFAULT GUID, i int)'
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'insert into t2(i) values(1)'
+assertcnt t2 1
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t2'
+
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2 { 
+schema 
+{
+    byte  auto_guid[16] dbstore="GUID"
+    short i   
+    int   j
+}
+
+keys 
+{
+        "PK"=auto_guid
+}
+}'
+
+
+echo 'part of a transaction'
+
+echo begin > ins2.in
+for ((i=1;i<=$CNT;i++)) ; do
+    echo "insert into t2(i,j) values($i,$i)"
+done >> ins2.in
+echo commit >> ins2.in
+
+echo 'same as above but not part of a transaction'
+
+for ((i=1;i<=$CNT;i++)) ; do
+    echo "insert into t2(i,j) values($i,$((2*i)))"
+done >> ins2.in
+
+echo 'using cte for speed'
+echo "INSERT INTO t2 (i,j) WITH tblx(x) AS ( VALUES(1) UNION ALL SELECT x+1 FROM tblx where x < $CNT) SELECT x,($CNT-x) FROM tblx" >> ins2.in
+
+
+PARALLEL=10
+for ((j=1;j<=$PARALLEL;j++)) ; do
+   cdb2sql -f ins2.in ${CDB2_OPTIONS} $dbnm default > ins2_${j}.out &
+done
+
+echo wait for all above background inserts to complete
+wait
+
+set -x
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default 'select * from t2' > content2.out
+echo 'failure in transactions inserting will mean count will be off'
+assertcnt t2 $((CNT*PARALLEL*3))
+
+set +e 
+
+echo 'create table t3 { 
+schema 
+{
+    byte auto_guid[17] dbstore="UUID"
+    int  i
+}
+}' > t3.in
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default "`cat t3.in`" &> t3.err
+
+echo "[`cat t3.in`] failed with rc 240 Error at line   4: CAN ONLY HAVE BYTE[16] FOR GUID DBSTORE: auto_guid
+" > t3.expected
+
+if ! diff t3.err t3.expected ; then
+    failexit "t3.err not as expected diff $PWD/{t3.err,t3.expected}"
+fi
 
 rm *.out
 echo "Success"
