Pass image name as an argument to dockerfile; Extend runit to take custom commands or a script

diff --git a/tests/docker/runit b/tests/docker/runit
--- a/tests/docker/runit
+++ b/tests/docker/runit
@@ -1,30 +1,50 @@
 #!/bin/bash
 
-set -x
+set -e
 
-if [[ $# -ne 2 ]]; then
-    echo Usage: /path/to/source cluster
+while [[ $1 = -* ]]; do
+    if [[ "$1" = "--source" ]]; then
+        shift
+        src=$1
+    elif [[ "$1" = "-n" ]] || [[ "$1" = "--numnodes" ]]; then
+        shift
+        numnodes=$1
+    elif [[ "$1" = "-c" ]] || [[ "$1" = "--commands" ]]; then
+        shift
+        commands=$1
+    elif [[ "$1" = "--script" ]]; then
+        shift
+        script=$1
+    fi
+    shift
+done
+
+
+if [[ "$src" = "" ]] || [[ "$numnodes" = "" ]]; then
+    echo "Usage: $0 --source source_directory -n numnodes [-c commands] [--script file]" >&2
     exit 1
 fi
 
-rm -fr common 
+rm -fr common
 mkdir common
-src=$1
-numnodes=$2
 for node in $(seq 1 $numnodes); do
     cluster="$cluster m${node}"
 done
 
-dir=$(pwd)
-
-cd $src
-prefix=$(git rev-parse --short HEAD)
+prefix="$(git --git-dir "$src/.git" rev-parse --short HEAD)"
+if [[ "$prefix" = "" ]]; then
+    echo 'Could not get the revision.' >&2
+    exit 1
+fi
 export COMPOSE_PROJECT_NAME=$prefix
-docker build -t comdb2test:$prefix -f $src/tests/docker/Dockerfile.dev .
-cd $dir
+
+if [[ "$script" != "" ]]; then
+    cp $script $src/user_script
+    chmod +x $src/user_script
+fi
+docker build -t comdb2test:$prefix -f $src/tests/docker/Dockerfile.install $src
 
 cp -r $src/tests/docker/* .
-sed -i.bak "s/@image@/comdb2test:$prefix/" Dockerfile.db
 echo $cluster >common/cluster
 ssh-keygen -N "" -f common/id_rsa
 
@@ -38,9 +58,11 @@ services:
         build:
             context: .
             dockerfile: Dockerfile.db
+            args:
+                - REVISION=$prefix
         volumes:
             - ./common:/common
-        command: /client
+        command: /client "$commands"
         cap_add:
             - SYS_PTRACE
 EOF
@@ -52,9 +74,11 @@ cat >> $compose <<EOF
         build:
             context: .
             dockerfile: Dockerfile.db
+            args:
+                - REVISION=$prefix
         volumes:
             - ./common:/common
-        command: /database
+        command: /server
         cap_add:
             - SYS_PTRACE
 EOF
@@ -62,5 +86,5 @@ done
 
 docker-compose build
 docker-compose up --abort-on-container-exit
-docker-compose down --rmi all
-docker-compose rm
+docker-compose down --rmi all --volumes
+docker-compose rm -f
