fix null param again

diff --git a/tests/basic.test/runit b/tests/basic.test/runit
--- a/tests/basic.test/runit
+++ b/tests/basic.test/runit
@@ -257,6 +257,21 @@ echo "[select * from t2] failed with rc -3 no such table: t2" > badsel.exp
 if ! diff badsel.txt badsel.exp ; then
     failexit "Expected failure when selecting nonexistent table"
 fi
+
+cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t2 (i int primary key)"
+cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t2 values(1)"
+cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t2 values(1)" &> dupins.txt
+echo "[insert into t2 values(1)] failed with rc 299 add key constraint duplicate key 'COMDB2_PK' on table 't2' index 0" > dupins.exp
+if ! diff  dupins.txt dupins.exp; then
+    failexit "Expected failure when executing bad procedure"
+fi
+cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t2 values(2)" &> dupins.txt
+cdb2sql ${CDB2_OPTIONS} $dbnm default "update t2 set i=1 where i=2" &> dupupd.txt
+echo "[update t2 set i=1 where i=2] failed with rc 299 add key constraint duplicate key 'COMDB2_PK' on table 't2' index 0" > dupupd.exp
+if ! diff  dupupd.txt dupupd.exp; then
+    failexit "Expected failure when executing bad procedure"
+fi
+
 cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure nonexistent(4)" &> badproc.txt
 echo "[exec procedure nonexistent(4)] failed with rc -3 no such procedure: nonexistent ver:0" > badproc.exp
 if ! diff badproc.txt badproc.exp ; then
