Log errors correctly in eventlog (#451)
Currently for a sql that produces error, ex:

basic21012> select * from t2;
[select blabla from t2] failed with rc -3 no such table: t2

we only log the error and not the sql. This patch allows to log
the sql as well as original newsql entry for such sql errors:

{"time": 1507920821394333, "type": "sql", "sql": "select * from t2", 
"error_code": 1, "error": "no such table: t2",
"host": "pnj-comdb2btda1","fingerprint": "f35131d02367794fd3d00000b7502624",
"qtime": 7,"context": ["cdb2sql"],"perf": {"runtime": 332}
}

diff --git a/tests/basic.test/runit b/tests/basic.test/runit
--- a/tests/basic.test/runit
+++ b/tests/basic.test/runit
@@ -251,6 +251,19 @@ cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t2  { `cat alltypes.csc2 ` }
 cdb2sql ${CDB2_OPTIONS} $dbnm default "alter table t2  { `cat alltypes.csc2 ` }"
 cdb2sql ${CDB2_OPTIONS} $dbnm default "drop table t2 "
 
+set +e
+cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t2 " &> badsel.txt
+echo "[select * from t2] failed with rc -3 no such table: t2" > badsel.exp
+if ! diff badsel.txt badsel.exp ; then
+    failexit "Expected failure when selecting nonexistent table"
+fi
+cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure nonexistent(4)" &> badproc.txt
+echo "[exec procedure nonexistent(4)] failed with rc -3 no such procedure: nonexistent ver:0" > badproc.exp
+if ! diff badproc.txt badproc.exp ; then
+    failexit "Expected failure when executing bad procedure"
+fi
+set -e
+
 INITNUMREC=100
 
 assert_vers t1 0
