convert sp.test to run via testopts; check default tran is snapshot

diff --git a/tests/basic.test/runit b/tests/basic.test/runit
--- a/tests/basic.test/runit
+++ b/tests/basic.test/runit
@@ -28,6 +28,15 @@ for required in $vars; do
 #    echo "$required=$q"
 done
 
+if echo $DBNAME | grep "snapshotgenerated" ; then
+    lvl=$(cdb2sql ${CDB2_OPTIONS} $DBNAME default "select value from comdb2_tunables where name='sql_tranlevel_default'")
+    if [ $lvl != "SNAPSHOT ISOLATION" ] ; then
+       echo "FAILURE: DB is not running in snapshot isolation mode"
+       exit 1
+    fi
+    cdb2sql ${CDB2_OPTIONS} $DBNAME default "@send get_newsi_status" 
+fi
+
 
 failexit()
 {
diff --git a/tests/sp.test/runit b/tests/sp.test/runit
--- a/tests/sp.test/runit
+++ b/tests/sp.test/runit
@@ -1,68 +1,27 @@
 #!/usr/bin/env bash
 bash -n "$0" | exit 1
 
+set -x
 dbname=$1
+
+if echo $dbname | grep "snapshotgenerated" ; then
+    lvl=$(cdb2sql ${CDB2_OPTIONS} $dbname default "select value from comdb2_tunables where name='sql_tranlevel_default'")
+    if [ $lvl != "SNAPSHOT ISOLATION" ] ; then
+       echo "FAILURE: DB is not running in snapshot isolation mode"
+       exit 1
+    fi
+    cdb2sql ${CDB2_OPTIONS} $dbname default "@send get_newsi_status" 
+fi
+
 
 echo "Starting socksql tests"
 echo "Using SP_OPTIONS: $SP_OPTIONS"
 ./test.sh $dbname
 rc=$?
+
 if (( $rc != 0 )) ; then
-   echo "SOCKSQL FAILURE"
+   echo "FAILURE"
    exit 1
 fi
 
-echo "SOCKSQL SUCCESS"
-
-cdb2config=$CDB2_CONFIG
-cdb2options=$CDB2_OPTIONS
-snapdb=snapshot$dbname
-dbdir=$DBDIR
-
-DBNAME=$snapdb
-DBDIR=$TESTDIR/$DBNAME
-CDB2_CONFIG=$DBDIR/comdb2db.cfg
-CDB2_OPTIONS="--cdb2cfg $CDB2_CONFIG"
-
-echo "sql_tranlevel_default snapisol" > "$TESTDIR/customlrl"
-export CUSTOMLRLPATH=$TESTDIR/customlrl
-
-#setup another db with default transaction snapisol
-echo "Setting up snapshot db"
-timeout 2m ${TESTSROOTDIR}/setup &> >(gawk '{ print strftime("%H:%M:%S>"), $0; fflush(); }' | tee ${TESTDIR}/logs/${DBNAME}.setup | cut -c11- | grep "^!" )
-rc=$?
-if [[ $rc -ne 0 ]]; then
-    echo "snapshot db setup failed (rc=$rc)"
-    $TESTSROOTDIR/unsetup &> >(gawk '{ print strftime("%H:%M:%S>"), $0; fflush(); }' | tee ${TESTDIR}/logs/${DBNAME}.unsetup | cut -c11- | grep "^!" )
-    DBNAME=$dbname
-    DBDIR=$dbdir
-    CDB2_CONFIG=$cdb2config
-    CDB2_OPTIONS=$cdb2options
-    CUSTOMLRLPATH=''
-    exit 1
-fi
-
-echo "Starting snapshot tests"
-SP_OPTIONS="-s --cdb2cfg $CDB2_CONFIG $DBNAME default"
-echo "Using SP_OPTIONS: $SP_OPTIONS"
-./test.sh $snapdb
-rc=$?
-
-echo "Cleaning up snapshot db"
-successful=1
-if (( $rc != 0 )) ; then
-    successful=0
-fi
-${TESTSROOTDIR}/unsetup $successful &> >(gawk '{ print strftime("%H:%M:%S>"), $0; fflush(); }' | tee ${TESTDIR}/logs/${DBNAME}.unsetup | cut -c11- | grep "^!" )
-
-DBNAME=$dbname
-DBDIR=$dbdir
-CDB2_CONFIG=$cdb2config
-CDB2_OPTIONS=$cdb2options
-
-if (( $rc != 0 )) ; then
-   echo "SNAPSHOT FAILURE"
-   exit 1
-fi
-
-echo "SNAPSHOT SUCCESS"
+echo "SUCCESS"
