SQL: Support for START TRANSACTION

diff --git a/tests/basic.test/runit b/tests/basic.test/runit
--- a/tests/basic.test/runit
+++ b/tests/basic.test/runit
@@ -9,7 +9,7 @@ debug=0
 
 dbnm=$1
 
-if [ "x$dbnm" == "x" ] ; then
+if [[ -z $dbnm ]] ; then
     echo "need a DB name"
     exit 1
 fi
@@ -329,5 +329,27 @@ cdb2sql ${CDB2_OPTIONS} $dbnm default 'exec procedure sys.cmd.send("sql hist")'
 
 res=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select 1"`
 assertres $res 1
+
+echo "transaction"
+
+for testreq in `ls t*.sql` ; do
+    testname=`echo $testreq | cut -d "." -f 1`
+    cmd="cdb2sql -s -f $testreq ${CDB2_OPTIONS} $dbnm default "
+    echo $cmd "> $testname.output"
+    $cmd 2>&1 | perl -pe "s/.n_writeops_done=([0-9]+)/rows inserted='\1'/; s/BLOCK2_SEQV2\(824\)/BLOCK_SEQ(800)/; s/OP #2 BLOCK_SEQ/OP #3 BLOCK_SEQ/;" > $testname.output
+
+    cmd="diff $testname.expected $testname.output"
+    $cmd > /dev/null
+
+    if [[  $? -eq 0 ]]; then
+        echo "passed $testname"
+    else
+        echo "failed $testname"
+        echo "see diffs here: $HOSTNAME"
+        echo "> diff ${PWD}/{$testname.expected,$testname.output}"
+        echo
+        exit 1
+    fi
+done
 
 echo "Success"
