Start to develop test suite.

diff --git a/tests/phys_reptest.test/runit b/tests/phys_reptest.test/runit
--- a/tests/phys_reptest.test/runit
+++ b/tests/phys_reptest.test/runit
@@ -7,7 +7,39 @@ NRUNS=10000
 
 set -x
 
-schema='create table t1 {
+destdb=${TESTCASE}dest${TESTID}
+DEST_DBDIR=${DBDIR}/$destdb
+mkdir -p $DEST_DBDIR
+
+# use copycomdb2 to create a physical replicant
+
+$COPYCOMDB2_EXE -H ${destdb} -y localhost $DEST_DBDIR/${destdb}.lrl
+
+df $DBDIR | awk '{print $1 }' | grep "tmpfs\|nfs" && echo "setattr directio 0" >> $DBDIR/${destdb}.lrl
+
+if [ -n "$PMUXPORT" ] ; then
+    echo "portmux_port $PMUXPORT" >> $DEST_DBDIR/${destdb}.lrl
+    echo "portmux_bind_path $pmux_socket" >> $DEST_DBDIR/${destdb}.lrl
+fi
+
+out=
+while [[ "$out" != "1" ]]; do
+    out=$(cdb2sql --tabs ${CDB2_OPTIONS} $destdb local 'select 1' 2>/dev/null)
+    sleep 1
+done
+
+# iterate over each test
+for sql in `ls *.sql | sort -V`; do
+    src=$(cdb2sql -s --tabs -f $sql ${CDB2_OPTIONS} $dbnme default 2>&1) 
+    dest=$(cdb2sql -s --tabs -f $sql ${CDB2_OPTIONS} $destdb localhost 2>&1)
+    if [ "$?" != "0" ]; then
+        echo 'Failed.'
+        exit 1
+    fi
+done
+
+# check add, insert, update
+cdb2sql ${CDB2_OPTIONS} $dbname default 'create table t1 {
 schema {
     int id
 
@@ -22,12 +54,14 @@ schema {
     blob i null=yes
     datetime j null=yes
 
-    longlong comdb2_seqno null=yes
 }
 }
 '
 
-cdb2sql ${CDB2_OPTIONS} $dbname default $schema
+
+src_add_table=$(cdb2sql ${CDB2_OPTIONS} $dbname default "select * from t1" | sort | md5sum)
+dest_add_table=$(cdb2sql ${CDB2_OPTIONS} $destdb local "select * from t1" | sort | md5sum)
+echo "src $src dest $dest"
 
 for i in $(seq 1 $NRECS); do
     echo "insert into t1 (id, a, b, c, d, e, f, g, h, i, j) values ($i, 1, 2, 3, 4, 5, 6.000000, 7.000000, 'eight', x'99', now());"
@@ -46,40 +80,8 @@ for i in $(seq 1 $NRUNS); do
     esac
 done | cdb2sql -s ${CDB2_OPTIONS} $dbname default - >/dev/null
 
-destdb=${TESTCASE}dest${TESTID}
-DBDIR=${DBDIR}/$destdb
-mkdir -p $DBDIR
-
-# use copycomdb2 to create a physical replicant
-
-cat > $DBDIR/${destdb}.lrl <<EOF
-name    $destdb
-dir     $DBDIR
-EOF
-
-df $DBDIR | awk '{print $1 }' | grep "tmpfs\|nfs" && echo "setattr directio 0" >> $DBDIR/${destdb}.lrl
-
-if [ -n "$PMUXPORT" ] ; then
-    echo "portmux_port $PMUXPORT" >> $DBDIR/${destdb}.lrl
-    echo "portmux_bind_path $pmux_socket" >> $DBDIR/${destdb}.lrl
-fi
-
-comdb2 $destdb -create -lrl $DBDIR/${destdb}.lrl 
-comdb2 $destdb -lrl $DBDIR/${destdb}.lrl -pidfile $DBDIR/${destdb}.pid &
-
-out=
-while [[ "$out" != "1" ]]; do
-    out=$(cdb2sql --tabs ${CDB2_OPTIONS} $destdb local 'select 1' 2>/dev/null)
-    sleep 1
-done
-
-# manually create another master to test exposed apply
-cdb2sql ${CDB2_OPTIONS} $destdb local $schema
-
-# finally run the replication step
-${TESTSBUILDDIR}/localrep $dbname $destdb 2>&1
-src=$(cdb2sql ${CDB2_OPTIONS} $dbname default "select * from t1" | sort | md5sum)
-dest=$(cdb2sql ${CDB2_OPTIONS} $destdb local "select * from t1" | sort | md5sum)
+src_rand=$(cdb2sql ${CDB2_OPTIONS} $dbname default "select * from t1" | sort | md5sum)
+dest_rand=$(cdb2sql ${CDB2_OPTIONS} $destdb local "select * from t1" | sort | md5sum)
 echo "src $src dest $dest"
 
 echo "Testing truncate table"
@@ -90,10 +92,10 @@ src2=$(cdb2sql ${CDB2_OPTIONS} $dbname default "select * from t1" | sort | md5su
 dest2=$(cdb2sql ${CDB2_OPTIONS} $destdb local "select * from t1" | sort | md5sum)
 echo "src2 $src2 dest2 $dest2"
 
-kill -9 $(cat $DBDIR/${destdb}.pid)
-
-echo deregister from pmux ${destdb}
-${TESTSROOTDIR}/tools/send_msg_port.sh "del comdb2/replication/${destdb} " ${pmux_port}
+# cleanup
+# kill -9 $(cat $DBDIR/${destdb}.pid)
+# echo deregister from pmux ${destdb}
+# ${TESTSROOTDIR}/tools/send_msg_port.sh "del comdb2/replication/${destdb} " ${pmux_port}
 
 if [[ "$src" != "$dest" ]]; then
     exit 1
