Modifying testcase.

diff --git a/tests/datetimeusec.test/runit b/tests/datetimeusec.test/runit
--- a/tests/datetimeusec.test/runit
+++ b/tests/datetimeusec.test/runit
@@ -100,10 +100,24 @@ echo "client typed (server milli -> client micro) query failed."
 exit 1
 fi
 
+cnt=`cdb2sql ${CDB2_OPTIONS} $dbnm default 'select cast("2017-07-14T183510.006" as datetime)' 9 | grep -c '2017-07-14T183510.006000'`
+if [[ $cnt -ne 1 ]]
+then
+echo "client typed (server milli -> client micro) query failed."
+exit 1
+fi
+
 cnt=`cdb2sql ${CDB2_OPTIONS} $dbnm default 'select now(6)' 6 | cut -d' ' -f1 | cut -d'.' -f2 | wc -c`
 if [[ $cnt -ne 4 ]]
 then
 echo "client typed (server micro -> client milli) query failed."
+exit 1
+fi
+
+cnt=`cdb2sql ${CDB2_OPTIONS} $dbnm default 'select cast("2017-07-14T183510.000003" as datetime)' 6 | grep -c '2017-07-14T183510.000'`
+if [[ $cnt -ne 1 ]]
+then
+echo "client typed (server milli -> client micro) query failed."
 exit 1
 fi
 
