Speedup truncate: cache version_num in process_unused_files (#2660)
When a db has many tables tables, truncate will take a long time because
delfiles will go through the entire directory to find files matching pattern
to be put in list for deletion. The inneficiency is because we fetch
version_num for every file in the directory: this checkin improves that
by caching those values in an array.
Also dont check if table is under schemachange when we have tbllock on it.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

diff --git a/tests/sc_lotsoftables.test/runit b/tests/sc_lotsoftables.test/runit
--- a/tests/sc_lotsoftables.test/runit
+++ b/tests/sc_lotsoftables.test/runit
@@ -4,11 +4,8 @@ bash -n "$0" | exit 1
 source ${TESTSROOTDIR}/tools/runit_common.sh
 source ${TESTSROOTDIR}/tools/cluster_utils.sh
 
-# Debug variable
-debug=0
-
 dbnm=$1
-tblcnt=150
+tblcnt=100
 
 if [ "x$dbnm" == "x" ] ; then
     echo "need a DB name"
@@ -33,23 +30,19 @@ function insert_records
         echo "insert into $tbl(a,b,c,d,e) values ($((j+10000)),'test1$j',$j,$j,'abc$j')" 
         let j=j+1
     done | cdb2sql ${CDB2_OPTIONS} $dbnm default - &>> $insfl
+    assertres $? 0
 }
 
-
-kill_by_pidfile() 
+function wait_till_ready
 {
-    pidfile=$1
-    if [[ -f $pidfile ]]; then
-        local pid=$(cat $pidfile)
-        ps -p $pid -o args | grep -q "comdb2 ${DBNAME}"
-        if [[ $? -eq 0 ]]; then
-            echo "kill -9 $pid"
-            kill -9 $pid
-        fi
-        rm -f $pidfile
-    else
-        failexit "kill_by_pidfile: pidfile $pidfile does not exist"
-    fi
+    node=$1
+    out=0
+    # wait until we can query it
+    echo "$DBNAME: waiting until ready"
+    while [[ "$out" != "1" ]]; do
+        sleep 2
+        out=$(cdb2sql ${CDB2_OPTIONS} --tabs --host $node $DBNAME  'select 1' 2>/dev/null)
+    done
 }
 
 kill_restart_cluster()
@@ -72,7 +65,6 @@ kill_restart_cluster()
     done
 }
 
-
 cluster=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'exec procedure sys.cmd.send("bdb cluster")' | grep lsn | cut -f1 -d':' `
 
 function flushall 
@@ -85,23 +77,39 @@ function flushall
 
 
 PRFIX=my_table_name_
+master=`cdb2sql -tabs ${CDB2_OPTIONS} $dbnm default 'exec procedure sys.cmd.send("bdb cluster")' | grep MASTER | cut -f1 -d":" | tr -d '[:space:]'`
+#cdb2sql ${CDB2_OPTIONS} $dbnm --host $master "exec procedure sys.cmd.send('bdb setattr DELAYED_OLDFILE_CLEANUP 0')"
 
 echo "Test with insert, SC should not fail"
 cdb2sql ${CDB2_OPTIONS} $dbnm default "create table ${PRFIX}0 { `cat t1_1.csc2 ` }"
+assertres $? 0
 
+echo "real time creating"
 #cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure sys.cmd.send('debg 500')"
 for i in `seq 1 $tblcnt`; do
   echo "create t$i: "
   time cdb2sql ${CDB2_OPTIONS} $dbnm default "create table ${PRFIX}$i  { `cat t1_1.csc2 ` }"
+  assertres $? 0
   insert_records ${PRFIX}$i $i
-  echo truncate ${PRFIX}0
-  time cdb2sql ${CDB2_OPTIONS} $dbnm default "truncate ${PRFIX}0"
-
   #flushall
 done
 
+echo "real time truncating"
+for i in `seq 1 20`; do
+  echo "truncate ${PRFIX}0"
+  time cdb2sql ${CDB2_OPTIONS} $dbnm default "truncate ${PRFIX}0"
+  
+  if [ $((i % 5)) == 0 ] ; then
+      echo delfiles ${PRFIX}0
+      time cdb2sql ${CDB2_OPTIONS} $dbnm --host $master "exec procedure sys.cmd.send('delfiles ${PRFIX}0')" &> delfiles.out
+  fi
+  insert_records ${PRFIX}0 1
+done
+
+echo "real time dropping"
 for i in `seq 1 $tblcnt`; do
     assertcnt ${PRFIX}$i $i
+    time cdb2sql ${CDB2_OPTIONS} $dbnm default "drop table ${PRFIX}$i"
     #echo rebuild t1
     #time cdb2sql ${CDB2_OPTIONS} $dbnm default "rebuild t1"
     #assertcnt t$i $i
@@ -118,7 +126,6 @@ done
 #    cdb2sql ${CDB2_OPTIONS} $dbnm --host $node "exec procedure sys.cmd.send('bdb setattr PRIVATE_BLKSEQ_MAXAGE 10')"
 #sleep 20
 
-#master=`cdb2sql -tabs ${CDB2_OPTIONS} $dbnm default 'exec procedure sys.cmd.send("bdb cluster")' | grep MASTER | cut -f1 -d":" | tr -d '[:space:]'`
 
 #for i in `seq 0 $tblcnt`; do
 #    assertcnt t$i $i
@@ -132,10 +139,11 @@ test_create_tbls() {
     tbl="f"
     while [ $i -lt 30 ] ; do
         tbl=$tbl$((i%10))
-        $CDB2SQL_EXE ${CDB2_OPTIONS} $dbnm default "create table $tbl (i int unique)"
+        $CDB2SQL_EXE ${CDB2_OPTIONS} $dbnm default "create table $tbl (i int unique, b blob)"
+        assertres $? 0
         val=$RANDOM
-        $CDB2SQL_EXE ${CDB2_OPTIONS} $dbnm default "insert into $tbl values ($val)"
-        res=`$CDB2SQL_EXE ${CDB2_OPTIONS} $dbnm --tabs default "select * from $tbl"`
+        $CDB2SQL_EXE ${CDB2_OPTIONS} $dbnm default "insert into $tbl values ($val, NULL)"
+        res=`$CDB2SQL_EXE ${CDB2_OPTIONS} $dbnm --tabs default "select i from $tbl"`
         assertres $res $val
         let i=i+1
     done
@@ -144,7 +152,12 @@ test_create_tbls() {
 
 test_create_tbls
 
-
+if [[ -n "$CLUSTER" ]] ; then
+    cdb2sql ${CDB2_OPTIONS} $dbnm --host master 'exec procedure sys.cmd.send("downgrade")'
+    for node in "$CLUSTER" ; do
+        wait_till_ready $node
+    done
+fi
 
 
 echo "Success"
