Fix deadlock test (#1137)
* fix the deadlock test to shut down cleanly threads

diff --git a/tests/deadlock.test/runit b/tests/deadlock.test/runit
--- a/tests/deadlock.test/runit
+++ b/tests/deadlock.test/runit
@@ -1,170 +1,179 @@
 #!/usr/bin/env bash
-bash -n "$0" | exit 1
 
-# Cursor moves testcase for comdb2
-################################################################################
-
-# debug=1
-
-# args
-a_dbn=$1
-
-export TMPDIR=${TMPDIR:-/tmp}
-export TESTDIR=${TESTDIR:-.}
+# deadlock policy tester for the cdb2tcm testsuite
 
 
-# find input files
-files=$( find . -type f -name \*.req | sort )
+# arguments 
+dbnm=$1
 
-# counter 
-nfiles=0
 
-# last batch
-last_batch=
+# generator and updater tasks
+gen=gen
+upd=upd
 
-# post-process
-pproc=cat
+keys[0]="a"
+keys[1]="b"
+keys[2]="c"
 
-# testcase output
-testcase_output=
+function gen {
+    db=$1
+    count=$2
+    i=1
+    while [[ $i -le $count ]]; do
+        echo "insert into t1(a, b, c) values($i, $i, $i)"
+        i=$(($i+1))
+    done | cdb2sql -s ${CDB2_OPTIONS} $db default - >/dev/null
+}
 
-# expected output
-expected_output=
+function upd {
+    db=$1
+    count=$(cdb2sql --tabs ${CDB2_OPTIONS} $db default 'select max(a) from t1')
+    while [ ! -f eotest.fl ] ; do
+        val=$(($RANDOM % $count))
+        key=$(($RANDOM % 3))
+        echo "select * from t1 where "${keys[$key]}" = $val limit 1"
+        echo "update t1 set a=$val where "${keys[$key]}" = $val"
+        ls -al eotest.fl >> debug.txt
+        date >> debug.txt
+        sleep 0.01
+    done | cdb2sql -s ${CDB2_OPTIONS} $db default - &> run_${RANDOM}.txt
+}
 
-# fastinit
-function fastinit
+
+
+# fork & timeout an executable after a period of time
+function run_timeout
 {
-    # print debug trace
-    [[ "$debug" == "1" ]] && set -x
+    # local vars
+    typeset st
+    typeset et
+    typeset elapsed=0
+    typeset cpid=0
 
-    # args
-    typeset db=$1
-    typeset iter=$2
-    typeset tbl
+    # arguments
+    exe=$1
+    args=$2
+    tmout=$3
 
-    # flagged?
-    if [[ ! -f $iter.fastinit ]]; then
-        return 0
-    fi
+    # SECONDS returns the number of seconds since the shell was invoked
+    st=$SECONDS
+    
+    # run command and grab pid
+    $exe $args > /dev/null 2>&1 &
+    cpid=$!
 
-    # fastinit
-    for tbl in $(cat $iter.fastinit) ; do
-        cdb2sql ${CDB2_OPTIONS} $db default "truncate $tbl"
+    echo verify pid = $cpid >> /dev/shm/pidverify.txt
+    # verify pid
+    ps -p $cpid >/dev/null 2>&1
+
+    while [[ $? == 0 && $elapsed -lt $tmout ]] ; do
+
+        sleep 1
+
+        # check to see if it's time to break out of the loop
+        et=$SECONDS
+        elapsed=$(( et - st ))
+
+        # verify pid
+        ps -p $cpid >/dev/null 2>&1
+
+    done
+
+    touch eotest.fl
+    sleep 2
+
+    # kill the background task
+    kill -9 $cpid >/dev/null 2>&1 
+    return 0
+}
+
+
+# run several instances of a program for a period of time
+function spawn_instances
+{
+    # local vars
+    typeset cnt=0
+
+    # arguments
+    exe=$1
+    args=$2
+    tmout=$3
+    inst=$4
+
+    # spawn several instances 
+    while [[ $cnt -lt $inst ]]; do
+
+        run_timeout $exe $args $tmout &
+        let cnt=cnt+1
+
     done
 
     return 0
 }
 
-# archcode function
-function myarch
+# run a select statement- verify that the output is correct
+function test_select
 {
-    # print debug trace
-    [[ "$debug" == "1" ]] && set -x
+    # local vars
+    typeset fil
+    typeset cnt=0
+    typeset err=0
 
-    u=$(uname)
-    a="<unknown>"
-    [[ "$u" == "SunOS" ]]   && a="sundev1"
-    [[ "$u" == "AIX" ]]     && a="ibm"
-    [[ "$u" == "HP-UX" ]]   && a="hp"
-    [[ "$u" == "Linux" ]]   && a="linux"
+    # arguments
+    dbnm=$1
+    iter=$2
 
-    echo $a
-    return 0
+    # select 
+    while [[ $cnt -lt $iter ]] ; do 
+
+        fil=${TMPDIR}/tsel.$cnt
+        cdb2sql -s ${CDB2_OPTIONS} $dbnm default "select * from t1 where a>0" >/dev/null 2>$fil &
+        let cnt=cnt+1
+
+    done
+
+    # wait for selects to complete
+    sleep 20
+
+    # zap
+    cnt=0
+
+    # print the output
+    while [[ $cnt -lt $iter ]] ; do 
+        [[ -s $fil ]] && err=1
+        cat $fil
+        let cnt=cnt+1
+
+    done
+
+    if [[ 0 == "$err" ]]; then
+        echo "SUCCESS!"
+    fi
+
 }
 
-# run tool
-function runtool
-{
-    # print debug trace
-    [[ "$debug" == "1" ]] && set -x
 
-    # args
-    typeset tool=$1
-    typeset args=$2
-    typeset db=$3
-
-    # run
-    $tool "$args" $db
-}
+# generate 10000 records of input data
+$gen $dbnm 10000
 
 
-# Iterate through input files
-for testcase in $files ; do
+# start 40 updaters - allow them to run for a minute
+spawn_instances $upd $dbnm 60 40
 
-    # increment counter
-    let nfiles=nfiles+1
 
-    # cleanup testcase
-    testcase=${testcase##*/}
-    
-    # see if the prefix has changed
-    new_batch=${testcase%%_*}
+# sleep for a few seconds
+sleep 10
 
-    # set output
-    output=${testcase}.res
-    
-    # fastinit if requested
-    if [[ $new_batch != $last_batch ]] ; then
 
-        fastinit $a_dbn $new_batch
-        last_batch=$new_batch
+# spawn 40 selects against an index
+test_select $dbnm 10 > t1_01.req.out
 
-    fi
+sleep 5
 
-    if  [[ -f $new_batch.tool ]] ; then
-
-        tool=$( cat $new_batch.tool )
-        args=$( cat $new_batch.args )
-        echo "runtool $tool \"$args\" $a_dbn > $output 2>&1"
-        runtool $tool "$args" $a_dbn > $output 2>&1
-
-    else
-
-        # Be verbose
-        cmd="cdb2sql ${CDB2_OPTIONS} $a_dbn default - < $testcase > $output 2>&1"
-        echo $cmd
-        # run command
-        eval $cmd
-
-    fi
-
-    # post-process
-    if [[ -f $new_batch.post ]]; then
-
-        # zap file
-        > $output.postprocess
-
-        # collect post-processing tool
-        pproc=$(cat $new_batch.post)
-
-        # post-process output
-        $pproc $output >> $output.postprocess
-
-        # copy post-processed output to original
-        mv $output.postprocess $output
-    fi
-
-    # get testcase output
-    testcase_output=$(cat $output)
-
-    # get expected output
-    expected_output=$(cat $testcase.out)
-
-    # verify 
-    if [[ "$testcase_output" != "$expected_output" ]]; then
-
-        echo "  ^^^^^^^^^^^^"
-        echo "The above testcase (${testcase}) has failed!!!"
-        echo " "
-        echo "Use 'diff <expected-output> <my-output>' to see why:"
-        echo "> diff ${PWD}/{$testcase.out,$output}"
-        echo " "
-        diff $testcase.out $output
-        echo " "
-        exit 1
-
-    fi
-
-done
+if ! diff t1_01.req.out t1_01.req.exp ; then
+    echo "diff ${PWD}/t1_01.req.{out,exp}"
+    echo "^^^^^^ failed"
+    exit 1
+fi
 
 echo "Testcase passed."
