Stop running tests if more than 10 tests failed
Check in runtestcase and exit if there were more than N (10) tests
that failed in order not to waste time and fill in the disk with
cores and results from obviously defective code.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

diff --git a/tests/runtestcase b/tests/runtestcase
--- a/tests/runtestcase
+++ b/tests/runtestcase
@@ -247,6 +247,16 @@ verify_db_at_finish() {
     done
 }
 
+stop_if_more_than_n_failed () {
+    N=10   # if more that N failures in test.log stop running
+    F=`grep failed ${TESTDIR}/test.log | wc -l`
+    if [ "$F" -ge "$N" ] ; then 
+        exit 1; 
+    fi
+}
+
+stop_if_more_than_n_failed
+
 
 # start the testing: setup, runit, check cores, unsetup
 
