Squash for sign-off
Signed-off-by: Morgan Douglas <mdouglas47@bloomberg.net>

diff --git a/tests/runtestcase b/tests/runtestcase
--- a/tests/runtestcase
+++ b/tests/runtestcase
@@ -246,6 +246,31 @@ find_cores() {
     done
 }
 
+verify_physical_at_finish() {
+    local LCLDBNM="$1"
+    local LCLCONFIG="$2"
+    local LCLOPTIONS="--cdb2cfg ${LCLCONFIG}"
+
+    if [[ -z "$CLUSTER" ]]; then
+        timeout 1m $CDB2SQL_EXE ${LCLOPTIONS} --tabs $LCLDBNM default "exec procedure sys.cmd.send('flush')" >/dev/null 2>&1
+        ls ${DBDIR}/ | egrep "\.datas|\.index|\.blobs" | while read fl ; do 
+            ${CDB2VERIFY_EXE} ${DBDIR}/$fl 
+            if [[ $? != 0 ]]; then
+                echo "${DBDIR}/$fl failed physical verify"
+                return
+            fi
+        done
+    else
+        for node in ${CLUSTER} ; do
+            timeout 1m $CDB2SQL_EXE ${LCLOPTIONS} --tabs $LCLDBNM --host $node "exec procedure sys.cmd.send('flush')" >/dev/null 2>&1
+            ck=`ssh -o StrictHostKeyChecking=no $node "ls ${DBDIR}/ | egrep \"\.datas|\.index|\.blobs\" | while read fl ; do ${CDB2VERIFY_EXE} ${DBDIR}/\\\${fl} ; if [[ \\\$? != 0 ]]; then echo \"$node:${DBDIR}/\\\${fl} failed verify\" ; break 2 ; fi ; done" < /dev/null`
+            if [[ -n "$ck" ]]; then
+                echo "$ck"
+                return
+            fi
+        done
+    fi
+}
 
 call_setup() {
     [[ $COMDB2_UNITTEST == 1 ]] && return
@@ -395,6 +420,7 @@ if [ $CHECK_DB_AT_FINISH -eq 1 ] ; then
         if [[ -z "${verify_ret}" ]] && [[ -n "${SECONDARY_DBNAME}" ]]; then
             verify_ret=`verify_db_at_finish ${SECONDARY_DBNAME} $SECONDARY_CDB2_CONFIG`
         fi
+        verify_phys=`verify_physical_at_finish ${DBNAME} $CDB2_CONFIG`
     fi
 fi
 
@@ -422,6 +448,12 @@ elif [[ -n "$verify_ret" ]] && [[ $rc -ne 0 ]] ; then
     echo "!$TESTCASE: failed" >> ${TEST_LOG}
     echo -e "!$TESTCASE: also ${RED}failed${NEUTRAL} verify ($verify_ret)"
     echo "!$TESTCASE: also failed verify ($verify_ret)" >> ${TEST_LOG}
+elif [[ -n "$verify_phys" ]] && [[ $rc -ne 0 ]]; then
+    echo "!$TESTCASE: failed rc=$rc (logs in ${TESTDIR}/logs/${DBNAME}.testcase)"
+    echo "!$TESTCASE: failed" >> ${TEST_LOG}
+    echo "!$TESTCASE: also failed physical-verify ($verify_phys)" | tee -a ${TEST_LOG}
+elif [[ -n "$verify_phys" ]]; then
+    echo "!$TESTCASE: failed physical-verify ($verify_phys)" | tee -a ${TEST_LOG}
 elif [[ -f "${DBNAME}.failexit" ]] ; then
     echo -e "!$TESTCASE: ${RED}failed${NEUTRAL} (found ${DBNAME}.failexit, logs in ${TESTDIR}/logs/${DBNAME}.testcase)"
     echo "!$TESTCASE: failed (found ${DBNAME}.failexit)" >> ${TEST_LOG}
