Use thread manager to register all running threads (#2801)
Use thread manager to register all running threads.
Also renamed some variables and removed some unnecessary includes.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

diff --git a/tests/runtestcase b/tests/runtestcase
--- a/tests/runtestcase
+++ b/tests/runtestcase
@@ -17,7 +17,7 @@ setup_debugger() {
             DEBUG_PREFIX="valgrind --track-origins=yes --log-file=$TESTDIR/$TESTCASE.valgrind"
             ;;
         memcheck)
-            DEBUG_PREFIX="valgrind  --leak-check=full --show-reachable=yes --track-origins=yes --leak-resolution=high --num-callers=30 --log-file=$TESTDIR/$TESTCASE.valgrind"
+            DEBUG_PREFIX="valgrind --leak-check=full --show-reachable=yes --track-origins=yes --leak-resolution=high --num-callers=30 --log-file=$TESTDIR/$TESTCASE.valgrind"
             ;;
         callgrind)
             DEBUG_PREFIX="valgrind --tool=callgrind --instr-atstart=no --dump-instr=yes --collect-systime=yes --collect-jumps=yes --callgrind-out-file=$TESTDIR/$TESTCASE.callgrind"
@@ -432,6 +432,20 @@ fi
 trap - INT EXIT
 
 call_unsetup
+
+# find any cores after unsetup -- ONLY works if CLEANUPDBDIR=0 because unsetup cleans up dir
+cr=`find_cores ${DBNAME} $DBDIR`
+
+if [[ -z "$cr" ]] && [[ -n "${SECONDARY_DBNAME}" ]] ; then
+    cr=`find_cores ${SECONDARY_DBNAME} ${SECONDARY_DBDIR}`
+fi
+
+
+if [[ -n "$cr" ]] ; then
+    echo "!$TESTCASE: at unsetup found core ($cr)" | tee -a ${TEST_LOG}
+    exit 1
+fi
+
 
 DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
 echo Done $TESTCASE with id $TESTID at $DATETIME >> ${TEST_LOG}
