Comdb2RLE + hintz (#79)
* Comdb2RLE with hints

This reduces CPU cycles reqd to compress with CRLE. Hints are sizes of
individual fields in a table. Compressed format is unchanged and old
software can still decode new output.

Fix DDL handler to specify compression algorithm during create-table.

CRLE unittests will be run by roborivers

* Enable gofast by default

* Call update_fld_hints() when both db->schema and db->handle are ready

set_bdb_option_flags() is better call site; it sets other bdb flags as
well.

* Free fld_hints on handle close

* Pick proper blob compression flags during update

diff --git a/tests/runtestcase b/tests/runtestcase
--- a/tests/runtestcase
+++ b/tests/runtestcase
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 TEST_TIMEOUT=${TEST_TIMEOUT:-5m}
 SETUP_TIMEOUT=${SETUP_TIMEOUT:-1m}
 
@@ -12,11 +11,13 @@ echo Starting $TESTCASE with id $TESTID at $DATETIME >> $TESTDIR/test.log
 mkdir -p ${TESTDIR}/logs/
 
 function call_unsetup {
+    [[ $TESTCASE == "crle" ]] && return
     ${TESTSROOTDIR}/unsetup $successful &> >(gawk '{ print strftime("%H:%M:%S>"), $0; fflush(); }' | tee ${TESTDIR}/logs/${DBNAME}.unsetup | cut -c11- | grep "^!" )
 }
 
 
 function call_setup {
+    [[ "$TESTCASE" == "crle" ]] && return
     timeout ${SETUP_TIMEOUT} ${TESTSROOTDIR}/setup &> >(gawk '{ t='${DBNAME}'; print strftime("%H:%M:%S>"), $0; fflush(); }' | tee ${TESTDIR}/logs/${DBNAME}.setup | cut -c11- | grep "^!" )
     rc=$?
     glist=`pgrep gawk -a | grep ${DBNAME} | cut -f1 -d' ' | xargs echo`
@@ -24,18 +25,16 @@ function call_setup {
         kill -9 $glist
     fi
     sleep 0.1
-    return $rc
+    if [[ $rc -ne 0 ]]; then
+        echo "!$TESTCASE: setup failed" >> ${TESTDIR}/test.log
+        echo "!$TESTCASE: setup failed see ${TESTDIR}/logs/${DBNAME}.setup"
+        call_unsetup
+        sleep 0.1
+        exit 1
+    fi
 }
 
 call_setup
-rc=$?
-if [[ $rc -ne 0 ]]; then
-    echo "!$TESTCASE: setup failed" >> ${TESTDIR}/test.log
-    echo "!$TESTCASE: setup failed see ${TESTDIR}/logs/${DBNAME}.setup"
-    call_unsetup
-    sleep 0.1
-    exit 1
-fi
 echo "!$TESTCASE: running"
 
 timeout ${TEST_TIMEOUT} ./runit ${DBNAME} 2>&1 | gawk '{ print strftime("%H:%M:%S>"), $0; fflush(); }' &> ${TESTDIR}/logs/${DBNAME}.testcase
@@ -53,9 +52,7 @@ else
     echo "!$TESTCASE: failed" >> ${TESTDIR}/test.log
 fi
 
-
 call_unsetup
-
 
 DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
 echo Done $TESTCASE with id $TESTID at $DATETIME >> $TESTDIR/test.log
