cdb2_verify database files at end of test
Signed-off-by: Mark Hannum <mhannum72@gmail.com>

Tighten verify-file requirements

Flush db before verifying

diff --git a/tests/runtestcase b/tests/runtestcase
--- a/tests/runtestcase
+++ b/tests/runtestcase
@@ -245,6 +245,31 @@ verify_db_at_finish() {
     done
 }
 
+verify_physical_at_finish() {
+    local LCLDBNM="$1"
+    local LCLCONFIG="$2"
+    local LCLOPTIONS="--cdb2cfg ${LCLCONFIG}"
+
+    if [[ -z "$CLUSTER" ]]; then
+        timeout 1m $CDB2SQL_EXE ${LCLOPTIONS} --tabs $LCLDBNM default "exec procedure sys.cmd.send('flush')"
+        ls ${DBDIR}/ | egrep "\.datas|\.index|\.blobs" | while read fl ; do 
+            ${CDB2VERIFY_EXE} ${DBDIR}/$fl 
+            if [[ $? != 0 ]]; then
+                echo "${DBDIR}/$fl failed physical verify"
+                return
+            fi
+        done
+    else
+        for node in ${CLUSTER} ; do
+            timeout 1m $CDB2SQL_EXE ${LCLOPTIONS} --tabs $LCLDBNM --host $node "exec procedure sys.cmd.send('flush')"
+            ck=`ssh -o StrictHostKeyChecking=no $node "ls ${DBDIR}/ | egrep \"\.datas|\.index|\.blobs\" | while read fl ; do ${CDB2VERIFY_EXE} ${DBDIR}/\\\${fl} ; if [[ \\\$? != 0 ]]; then echo \"$node:${DBDIR}/\\\${fl} failed verify\" ; break 2 ; fi ; done" < /dev/null`
+            if [[ -n "$ck" ]]; then
+                echo "$ck"
+                return
+            fi
+        done
+    fi
+}
 
 # start the testing: setup, runit, check cores, unsetup
 
@@ -300,6 +325,7 @@ if [ $CHECK_DB_AT_FINISH -eq 1 ] ; then
         if [[ -z "$verify_ret" ]] && [[ -n "${SECONDARY_DBNAME}" ]]; then
             verify_ret=`verify_db_at_finish ${SECONDARY_DBNAME} $SECONDARY_CDB2_CONFIG`
         fi
+        verify_phys=`verify_physical_at_finish`${DBNAME} $CDB2_CONFIG
     fi
 fi
 
@@ -317,8 +343,14 @@ elif [[ -n "$verify_ret" ]] && [[ ! $rc -eq 0 ]] ; then
     echo "!$TESTCASE: failed rc=$rc (logs in ${TESTDIR}/logs/${DBNAME}.testcase)"
     echo "!$TESTCASE: failed" >> ${TEST_LOG}
     echo "!$TESTCASE: also failed verify ($verify_ret)" | tee -a ${TEST_LOG}
+elif [[ -n "$verify_phys" ]] && [[ ! $rc -eq 0 ]]; then
+    echo "!$TESTCASE: failed rc=$rc (logs in ${TESTDIR}/logs/${DBNAME}.testcase)"
+    echo "!$TESTCASE: failed" >> ${TEST_LOG}
+    echo "!$TESTCASE: also failed physical-verify ($verify_phys)" | tee -a ${TEST_LOG}
 elif [[ -n "$verify_ret" ]] ; then
     echo "!$TESTCASE: failed verify ($verify_ret)" | tee -a ${TEST_LOG}
+elif [[ -n "$verify_phys" ]]; then
+    echo "!$TESTCASE: failed physical-verify ($verify_phys)" | tee -a ${TEST_LOG}
 elif [[ $rc -eq 0 ]] ; then
     echo "!$TESTCASE: success (logs in ${TESTDIR}/logs/${DBNAME}.testcase)"
     echo "!$TESTCASE: success" >> ${TEST_LOG}
