remove redundant code in in do_replay_case (#416)
* remove redundant code in in do_replay_case
* move set property after check for copying to cluster
* fix qcopy.test so it passes clustered test

diff --git a/tests/setup b/tests/setup
--- a/tests/setup
+++ b/tests/setup
@@ -188,12 +188,12 @@ if [ $? -eq 0 ] ; then
     COMDB2_PMUX_FILE="$TESTSROOTDIR/pmux.sqlite" $pmux_cmd
 fi
 
-set -e  # from here, a bad rc will mean failure and exit
 
 # if CLUSTER is length is nonzero, and file does not exist, copy to cluster
 if [ -n "$CLUSTER" ] ; then 
     { > $COPIEDTOCLUSTER ; } &> /dev/null 
     if [ $? -eq 0 ] ; then
+        set -e  # from here, a bad rc will mean failure and exit
         copy_files_to_cluster
     fi
 fi
