use ssh in master mode to route all ssh commands for test setup

diff --git a/tests/setup b/tests/setup
--- a/tests/setup
+++ b/tests/setup
@@ -179,27 +179,48 @@ fi
 stop_pmux="pgrep pmux > /dev/null && (exec 3<>/dev/tcp/localhost/${pmux_port} && echo exit >&3 ) || echo PMUX DOWN"
 
 COPIEDTOCLUSTER=${TMPDIR}/copiedtocluster.log
-export COMDB2AR_EXOPTS="-x $COMDB2_EXE"
+
+#use connection sharing via master node
+SSH_OPT="-o StrictHostKeyChecking=no -o ControlPath=$TESTDIR/%r%h%p"
+
+
+exiting()
+{
+    for node in ${CLUSTER/$HOSTNAME/}; do
+        ssh $SSH_OPT -O exit $node
+    done
+}
+
+start_ssh_master_cluster() 
+{
+    echo copying executables to each node except localhost
+    for node in ${CLUSTER/$HOSTNAME/}; do
+        if [ $node == $HOSTNAME ] ; then
+            echo "Error: hostname is in the CLUSTER list -HOSTNAME"
+            exit 1
+        fi
+        ssh $SSH_OPT -MNf $node
+    done
+    trap exiting EXIT
+}
+
 
 copy_files_to_cluster() 
 {
     echo copying executables to each node except localhost
-    for node in $CLUSTER; do
-        if [ $node == $HOSTNAME ] ; then
-            continue
-        fi
-        ssh -o StrictHostKeyChecking=no $node "mkdir -p ${SRCHOME} $d1 $d2 $d3 $d4 $TESTDIR/logs/ $TESTDIR/var/log/cdb2 $TESTDIR/tmp/cdb2" < /dev/null
-        scp -o StrictHostKeyChecking=no $COMDB2AR_EXE $node:$COMDB2AR_EXE
-        scp -o StrictHostKeyChecking=no $COMDB2_EXE $node:$COMDB2_EXE
-        scp -o StrictHostKeyChecking=no $CDB2SQL_EXE $node:$CDB2SQL_EXE
+    for node in ${CLUSTER/$HOSTNAME/}; do
+        ssh $SSH_OPT $node "mkdir -p ${SRCHOME} $d1 $d2 $d3 $d4 $TESTDIR/logs/ $TESTDIR/var/log/cdb2 $TESTDIR/tmp/cdb2" < /dev/null
+        scp $SSH_OPT $COMDB2AR_EXE $node:$COMDB2AR_EXE
+        scp $SSH_OPT $COMDB2_EXE $node:$COMDB2_EXE
+        scp $SSH_OPT $CDB2SQL_EXE $node:$CDB2SQL_EXE
         if [ -n "$RESTARTPMUX" ] ; then
             echo stop pmux on $node first before copying and starting it
-            ssh -o StrictHostKeyChecking=no $node "$stop_pmux" < /dev/null
+            ssh $SSH_OPT $node "$stop_pmux" < /dev/null
         fi
         set +e
-        scp -o StrictHostKeyChecking=no $PMUX_EXE $node:$PMUX_EXE
+        scp $SSH_OPT $PMUX_EXE $node:$PMUX_EXE
         echo start pmux on $node if not running 
-        ssh -o StrictHostKeyChecking=no $node "COMDB2_PMUX_FILE='$TESTSROOTDIR/pmux.sqlite' $pmux_cmd" < /dev/null
+        ssh $SSH_OPT $node "COMDB2_PMUX_FILE='$TESTSROOTDIR/pmux.sqlite' $pmux_cmd" < /dev/null
         set -e
     done
 }
@@ -217,8 +238,12 @@ if [ $? -eq 0 ] ; then
     COMDB2_PMUX_FILE="$TESTSROOTDIR/pmux.sqlite" $pmux_cmd
 fi
 
-# if CLUSTER is length is nonzero, and file does not exist, copy to cluster
+# if CLUSTER is length is nonzero
+
 if [ -n "$CLUSTER" ] ; then 
+    start_ssh_master_cluster
+
+    #if file does not exist, copy to cluster
     { > $COPIEDTOCLUSTER ; } &> /dev/null 
     if [ $? -eq 0 ] ; then
         set -e  # from here, a bad rc will mean failure and exit
@@ -277,8 +302,8 @@ check_db_port_running_node() {
         echo "pid running on dbport: $opid"
     [ -n "$opid" ] && ps -p $opid -o comm,args
     else
-        ssh -o StrictHostKeyChecking=no $node "netstat -na | grep $dbport" </dev/null
-        opid=`ssh -o StrictHostKeyChecking=no $node "fuser -n tcp $dbport" </dev/null`
+        ssh $SSH_OPT $node "netstat -na | grep $dbport" </dev/null
+        opid=`ssh $SSH_OPT $node "fuser -n tcp $dbport" </dev/null`
         echo "pid running on dbport: $opid"
     fi
     $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node:$dbport $DBNAME 'select comdb2_dbname()' 2>&1
@@ -315,11 +340,14 @@ if [[ -z "$CLUSTER" ]]; then
     done
 else
     echo "!$TESTCASE: copying to cluster"
+    COMDB2AR_AROPTS="-C preserve"
+    COMDB2AR_EXOPTS="-x $COMDB2_EXE"
+
+#$COMDB2AR_EXE $COMDB2AR_AROPTS c ${LRL} 2> $TESTDIR/logs/${DBNAME}.arstatus > $TESTDIR/${DBNAME}.ar
     for node in ${CLUSTER/$HOSTNAME/}; do
-        if [ $node == $HOSTNAME ] ; then
-            continue        # no copying to self
-        fi
-        comdb2ar="$COMDB2AR_EXE" $COPYCOMDB2_EXE ${LRL} ${node}: &> $TESTDIR/logs/${DBNAME}.${node}.copy
+        cat $TESTDIR/${DBNAME}.ar | ssh $SSH_OPT $node "$COMDB2AR_EXE $COMDB2AR_EXOPTS $COMDB2AR_AROPTS -u 95 x $DBDIR" &> $TESTDIR/logs/${DBNAME}.${node}.copy
+
+#comdb2ar="$COMDB2AR_EXE" $COPYCOMDB2_EXE ${LRL} ${node}: &> $TESTDIR/logs/${DBNAME}.${node}.copy
         if [[ $? -ne 0 ]]; then
             echo "FAILED: $COPYCOMDB2_EXE ${LRL} ${node}: "
             echo "see $TESTDIR/logs/${DBNAME}.${node}.copy "
@@ -343,8 +371,9 @@ else
         if [[ -n ${DEBUG_PREFIX} && ${INTERACTIVE_DEBUG} -eq 1 ]]; then
             echo -e "!$TESTCASE: Execute the following command on ${node}: ${TEXTCOLOR}${CMD}${NOCOLOR}"
         else
-            scp -o StrictHostKeyChecking=no ${TESTDIR}/replicant_vars $node:${TESTDIR}/replicant_vars
+            scp $SSH_OPT ${TESTDIR}/replicant_vars $node:${TESTDIR}/replicant_vars
             # redirect output from CMD to a subshell which runs awk to prepend time
+            # could also use connection sharing and close master ssh session in unsetup
             ssh -n -o StrictHostKeyChecking=no -tt $node ${CMD} &>$TESTDIR/logs/${DBNAME}.${node}.db &
             # $! will be pid of ssh (if we had used pipe, $! would be pid of awk)
             echo $! > ${TMPDIR}/${DBNAME}.${node}.pid
@@ -375,4 +404,8 @@ else
     done
 fi
 
+if [ -n "$CLUSTER" ] ; then 
+    trap - EXIT
+    exiting
+fi
 echo 'setup successful'
