copy db in parallel for tests (#838)
* Use ssh master session for copying exe
* Copy db in parallel to all nodes in a cluster for tests
* Cleanup better at end of test in nodes
* AR file in dbdir, local variables, fix total test counter
* Copy executables in background (parallel) as well, unsetup in parallel
* Update tests/README with more accurate instructions

diff --git a/tests/setup b/tests/setup
--- a/tests/setup
+++ b/tests/setup
@@ -172,8 +172,7 @@ if [ -n "${PMUXPORT}" ] ; then
     echo "portmux_bind_path $pmux_socket" >> ${LRL}
 fi
 
-export COMDB2AR_EXOPTS="-x $COMDB2_EXE"
-
+SSH_OPT="-o StrictHostKeyChecking=no "
 
 for csc2 in $(ls *.csc2 2>/dev/null); do
     table=${csc2%%.csc2}
@@ -198,24 +197,25 @@ echo "${DBNAME} created successfully"
 set -e
 
 check_db_port_running_local() {
-    dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
+    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
     if [ "x$dbport" == "x" ] ; then
         return
     fi
     echo "checking what is running on localhost:$dbport"
     netstat -na | grep $dbport
-    opid=`fuser -n tcp $dbport`
+    local opid=`fuser -n tcp $dbport`
     echo "pid running on dbport: $opid"
     [ -n "$opid" ] && ps -p $opid -o comm,args
     $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host localhost:$dbport $DBNAME 'select comdb2_dbname()' 2>&1
 }
 
 check_db_port_running_node() {
-    node=$1
-    dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.${node}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
+    local node=$1
+    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.${node}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
     if [ "x$dbport" == "x" ] ; then
         return;
     fi
+    local opid
     echo "checking what is running on ${node}:$dbport"
     if [ "$node" == "$HOSTNAME" ] ; then 
         netstat -na | grep $dbport
@@ -223,8 +223,8 @@ check_db_port_running_node() {
         echo "pid running on dbport: $opid"
     [ -n "$opid" ] && ps -p $opid -o comm,args
     else
-        ssh -o StrictHostKeyChecking=no $node "netstat -na | grep $dbport" </dev/null
-        opid=`ssh -o StrictHostKeyChecking=no $node "fuser -n tcp $dbport" </dev/null`
+        ssh $SSH_OPT $node "netstat -na | grep $dbport" </dev/null
+        opid=`ssh $SSH_OPT $node "fuser -n tcp $dbport" </dev/null`
         echo "pid running on dbport: $opid"
     fi
     $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node:$dbport $DBNAME 'select comdb2_dbname()' 2>&1
@@ -264,16 +264,29 @@ else
     if [[ -n "$NUMNODESTOUSE" ]]; then
         echo "$TESTCASE: cluster is $CLUSTER"
     fi
+    COMDB2AR_AROPTS="-C preserve"
+    COMDB2AR_EXOPTS="-x $COMDB2_EXE"
+
+    ARFILE=$DBDIR/${DBNAME}.ar
+    $COMDB2AR_EXE $COMDB2AR_AROPTS c ${LRL} 2> $TESTDIR/logs/${DBNAME}.arstatus > $ARFILE
+    [ ! -f $ARFILE ] && echo "failed to create $ARFILE" && exit 1
+
+    i=0
+    declare -a pids
     for node in ${CLUSTER/$HOSTNAME/}; do
-        if [ $node == $HOSTNAME ] ; then
-            continue        # no copying to self
-        fi
-        comdb2ar="$COMDB2AR_EXE" $COPYCOMDB2_EXE ${LRL} ${node}: &> $TESTDIR/logs/${DBNAME}.${node}.copy
+        cat $ARFILE | ssh $SSH_OPT $node "$COMDB2AR_EXE $COMDB2AR_EXOPTS $COMDB2AR_AROPTS -u 95 x $DBDIR" &> $TESTDIR/logs/${DBNAME}.${node}.copy &
+        pids[$i]=$!
+        let i=i+1
+    done
+    i=0
+    for node in ${CLUSTER/$HOSTNAME/}; do
+        wait ${pids[$i]}
         if [[ $? -ne 0 ]]; then
             echo "FAILED: $COPYCOMDB2_EXE ${LRL} ${node}: "
             echo "see $TESTDIR/logs/${DBNAME}.${node}.copy "
             exit 1
         fi
+        let i=i+1
     done
 
     echo "export COMDB2_ROOT=$COMDB2_ROOT" >> ${TESTDIR}/replicant_vars
@@ -292,9 +305,10 @@ else
         if [[ -n ${DEBUG_PREFIX} && ${INTERACTIVE_DEBUG} -eq 1 ]]; then
             echo -e "!$TESTCASE: Execute the following command on ${node}: ${TEXTCOLOR}${CMD}${NOCOLOR}"
         else
-            scp -o StrictHostKeyChecking=no ${TESTDIR}/replicant_vars $node:${TESTDIR}/replicant_vars
+            scp $SSH_OPT ${TESTDIR}/replicant_vars $node:${TESTDIR}/replicant_vars
             # redirect output from CMD to a subshell which runs awk to prepend time
-            ssh -n -o StrictHostKeyChecking=no -tt $node ${CMD} &>$TESTDIR/logs/${DBNAME}.${node}.db &
+            # could also use connection sharing and close master ssh session in unsetup
+            ssh -n $SSH_OPT -tt $node ${CMD} &>$TESTDIR/logs/${DBNAME}.${node}.db &
             # $! will be pid of ssh (if we had used pipe, $! would be pid of awk)
             echo $! > ${TMPDIR}/${DBNAME}.${node}.pid
         fi
