sc_seed no timebased genid, no 2: in front of comdb2_rowid (#883)
sc_seed to not have timebased genid because it screws with the genid48 generation and more:
* Use real get_genid for seed, machine and time info from hash value
* dont print '2:' in front of comdb2_rowid
* add to stripe test to print genid in hex and getting stripe from genid by modding it with 16
* better dumping to logs when setup and unsetup dbs from tests
* in setup, check for used port by checking pid as soon as possible rather than when a failing 'select 1'
* in unsetup, clean DBDIR from test runner node as well even when not part of cluster

diff --git a/tests/setup b/tests/setup
--- a/tests/setup
+++ b/tests/setup
@@ -12,7 +12,7 @@ while [[ $# -gt 0 && $1 = -* ]]; do
     shift
 done
 
-vars="HOSTNAME TESTID SRCHOME TESTCASE DBNAME DBDIR BUILDDIR TESTSBUILDDIR TESTSROOTDIR TESTDIR TMPDIR CDB2_OPTIONS CDB2_CONFIG COMDB2_EXE CDB2SQL_EXE COMDB2AR_EXE pmux_port"
+vars="HOSTNAME TESTID SRCHOME TESTCASE DBNAME DBDIR BUILDDIR TESTSBUILDDIR TESTSROOTDIR TESTDIR TMPDIR CDB2_OPTIONS CDB2_CONFIG COMDB2_EXE CDB2SQL_EXE COMDB2AR_EXE PMUX_EXE pmux_port"
 for required in $vars; do
     q=${!required}
     if [[ -z "$q" ]]; then
@@ -124,11 +124,11 @@ fi
 
 echo "logmsg level info" >> ${LRL}
 
-if [[ -f ${TESTDIR}/${TESTCASE}.test/lrl ]]; then
-    cat ${TESTDIR}/${TESTCASE}.test/lrl >> ${LRL}
+if [[ -f ${TESTSROOTDIR}/${TESTCASE}.test/lrl ]]; then
+    cat ${TESTSROOTDIR}/${TESTCASE}.test/lrl >> ${LRL}
 fi
-if [[ -f "${TESTDIR}/${TESTCASE}.test/lrl.options" ]]; then
-    cat ${TESTDIR}/${TESTCASE}.test/lrl.options >> ${LRL}
+if [[ -f "${TESTSROOTDIR}/${TESTCASE}.test/lrl.options" ]]; then
+    cat ${TESTSROOTDIR}/${TESTCASE}.test/lrl.options >> ${LRL}
 fi
 
 cat >> ${LRL} <<EOPTIONS
@@ -221,7 +221,7 @@ check_db_port_running_node() {
         netstat -na | grep $dbport
         opid=`fuser -n tcp $dbport`
         echo "pid running on dbport: $opid"
-    [ -n "$opid" ] && ps -p $opid -o comm,args
+        [ -n "$opid" ] && ps -p $opid -o comm,args
     else
         ssh $SSH_OPT $node "netstat -na | grep $dbport" </dev/null
         opid=`ssh $SSH_OPT $node "fuser -n tcp $dbport" </dev/null`
@@ -282,8 +282,7 @@ else
     for node in ${CLUSTER/$HOSTNAME/}; do
         wait ${pids[$i]}
         if [[ $? -ne 0 ]]; then
-            echo "FAILED: $COPYCOMDB2_EXE ${LRL} ${node}: "
-            echo "see $TESTDIR/logs/${DBNAME}.${node}.copy "
+            echo "FAILED: copying ${LRL} ${node}: see $TESTDIR/logs/${DBNAME}.${node}.copy"
             exit 1
         fi
         let i=i+1
@@ -314,15 +313,25 @@ else
         fi
     done
 
+    #check for failure in starting any of the nodes
+    sleep 1
+    for node in $CLUSTER; do
+        kill -0 `cat ${TMPDIR}/${DBNAME}.${node}.pid` > /dev/null
+        if [ $? -eq 1 ] ; then
+            echo "pid ${TMPDIR}/${DBNAME}.${node}.pid: `cat ${TMPDIR}/${DBNAME}.${node}.pid` is not alive"
+            check_db_port_running_node $node # this error is immediate so we should be able to catch it early
+        fi
+    done
+
     echo "!$TESTCASE: waiting until ready"
     for node in $CLUSTER; do
         set +e
+        echo "If we can't talk to any of the nodes the test will timeout"
         out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
         while  [[ "$out" != "1" ]]; do
             sleep 2
             out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
             $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' &> $TESTDIR/logs/${DBNAME}.${node}.conn
-            [[ "$out" != "1" ]] && check_db_port_running_node $node
         done
         $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select comdb2_host()' &>> $TESTDIR/logs/${DBNAME}.${node}.conn
         out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select comdb2_host()' 2>&1)
