change tests to use new setup

diff --git a/tests/setup b/tests/setup
--- a/tests/setup
+++ b/tests/setup
@@ -18,14 +18,7 @@ while [[ $# -gt 0 && $1 = -* ]]; do
     shift
 done
 
-# DBNAME looks like this: analyze_new_12758
-# DBNAME is the global main db name assigned from Makefile
-# In this script we want to take the db name we are setting up via
-# the first argument
-LCLDBNAME=$1
-LCLDBDIR=$2
-
-vars="HOSTNAME TESTID SRCHOME TESTCASE LCLDBNAME LCLDBDIR BUILDDIR TESTSBUILDDIR TESTSROOTDIR TESTDIR TMPDIR CDB2_OPTIONS CDB2_CONFIG COMDB2_EXE CDB2SQL_EXE COMDB2AR_EXE PMUX_EXE pmux_port"
+vars="HOSTNAME TESTID SRCHOME TESTCASE DBNAME DBDIR BUILDDIR TESTSBUILDDIR TESTSROOTDIR TESTDIR TMPDIR CDB2_OPTIONS CDB2_CONFIG COMDB2_EXE CDB2SQL_EXE COMDB2AR_EXE PMUX_EXE pmux_port"
 for required in $vars; do
     q=${!required}
     if [[ -z "$q" ]]; then
@@ -37,8 +30,7 @@ done
 
 source $TESTSROOTDIR/setup.common
 
-#get full path
-LCLDBDIR=$(readlink -f $LCLDBDIR)
+DBDIR=$(readlink -f $DBDIR)
 
 # Setup a debugger to run comdb2 server
 DEBUG_PREFIX=
@@ -114,9 +106,9 @@ if [[ $debug -eq 1 ]]; then
     [[ -n "$SKIPSSL" ]] && echo 'export SKIPSSL="'$SKIPSSL'"' >> $SETENV
     echo ". $SETENV" >> $RUNTEST
     echo "cd ${TESTSROOTDIR}/${TESTCASE}.test/" >> $RUNTEST
-    echo "./runit ${LCLDBNAME} \$1 " >> $RUNTEST
+    echo "./runit ${DBNAME} \$1 " >> $RUNTEST
     echo "echo; echo; echo;" >> $RUNTEST
-    echo "${TESTSROOTDIR}/unsetup $LCLDBNAME " >> $RUNTEST
+    echo "${TESTSROOTDIR}/unsetup" >> $RUNTEST
     echo
     echo
     chmod +x $SETENV
@@ -124,12 +116,13 @@ if [[ $debug -eq 1 ]]; then
 fi
 
 # TESTDIR looks like this: tests/test_12758
-# LCLDBDIR looks like this: tests/test_12758/analyzenew12758
-mkdir -p $LCLDBDIR $TMPDIR
+# DBDIR looks like this: tests/test_12758/analyzenew12758
+mkdir -p $DBDIR $TMPDIR
 
 # setup files:
+# DBNAME looks like this: analyze_new_12758
 echo "!$TESTCASE: creating"
-LRL="$LCLDBDIR/${LCLDBNAME}.lrl"
+LRL="$DBDIR/$DBNAME.lrl"
 > ${LRL}
 
 if [[ -z $SKIPSSL ]] ; then
@@ -149,8 +142,8 @@ if [[ -f lrl.options ]]; then
 fi
 
 cat >> ${LRL} <<EOPTIONS
-name    ${LCLDBNAME}
-dir     $LCLDBDIR
+name    $DBNAME
+dir     $DBDIR
 
 setattr MASTER_REJECT_REQUESTS 0
 EOPTIONS
@@ -159,12 +152,12 @@ if [[ -n "$CUSTOMLRLPATH" ]]; then
     cat $CUSTOMLRLPATH >> ${LRL}
 fi
 
-df $LCLDBDIR | awk '{print $1 }' | grep "tmpfs\|nfs" && echo "setattr directio 0" >> ${LRL}
+df $DBDIR | awk '{print $1 }' | grep "tmpfs\|nfs" && echo "setattr directio 0" >> ${LRL}
 echo "make_slow_replicants_incoherent off" >> ${LRL}
 
 # If CLUSTER is defined, populate config and lrl with that info
 if [[ -n "$CLUSTER" ]]; then
-    echo ${LCLDBNAME} 0 $CLUSTER > $CDB2_CONFIG
+    echo $DBNAME 0 $CLUSTER > $CDB2_CONFIG
     echo "comdb2_config:default_type=testsuite" >> $CDB2_CONFIG
     echo "cluster nodes $CLUSTER" >> ${LRL}
     if [[ -n "$DEDICATED_NETWORK_SUFFIXES" ]] ; then
@@ -193,29 +186,29 @@ SSH_OPT="-o StrictHostKeyChecking=no "
 
 for csc2 in $(ls *.csc2 2>/dev/null); do
     table=${csc2%%.csc2}
-    cp $PWD/$csc2 $LCLDBDIR/
+    cp $PWD/$csc2 $DBDIR/
 done >> ${LRL}
 
 mkdir -p $TESTDIR/var/log/cdb2 $TESTDIR/tmp/cdb2
-cd $LCLDBDIR >/dev/null
+cd $DBDIR >/dev/null
 
-PARAMS="${LCLDBNAME} --no-global-lrl"
+PARAMS="$DBNAME --no-global-lrl"
 export LOGDIR=$TESTDIR/logs
 
 # The script occasionally fails here. Let's find out what the rc is.
 set +e
-$COMDB2_EXE --create --lrl ${LRL} --pidfile ${TMPDIR}/${LCLDBNAME}.pid $PARAMS &> $LOGDIR/${LCLDBNAME}.init
+$COMDB2_EXE --create --lrl ${LRL} --pidfile ${TMPDIR}/$DBNAME.pid $PARAMS &> $LOGDIR/${DBNAME}.init
 rc=$?
-rm -f ${LCLDBNAME}.trap
+rm -f ${DBNAME}.trap
 if [[ $rc -ne 0 ]]; then
-    failexit "Error rc=$rc while initializing DB, see $LOGDIR/${LCLDBNAME}.init "
+    failexit "Error rc=$rc while initializing DB, see $LOGDIR/${DBNAME}.init "
 fi
-echo "${LCLDBNAME} created successfully"
+echo "${DBNAME} created successfully"
 
 set -e
 
 check_db_port_running_local() {
-    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $LOGDIR/${LCLDBNAME}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
+    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $LOGDIR/${DBNAME}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
     if [ "x$dbport" == "x" ] ; then
         return
     fi
@@ -224,12 +217,12 @@ check_db_port_running_local() {
     local opid=`fuser -n tcp $dbport`
     echo "pid running on dbport: $opid"
     [ -n "$opid" ] && ps -p $opid -o comm,args
-    $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host localhost:$dbport ${LCLDBNAME} 'select comdb2_dbname()' 2>&1
+    $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host localhost:$dbport $DBNAME 'select comdb2_dbname()' 2>&1
 }
 
 check_db_port_running_node() {
     local node=$1
-    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $LOGDIR/${LCLDBNAME}.${node}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
+    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $LOGDIR/${DBNAME}.${node}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
     if [ "x$dbport" == "x" ] ; then
         return;
     fi
@@ -245,13 +238,13 @@ check_db_port_running_node() {
         opid=`ssh $SSH_OPT $node "fuser -n tcp $dbport" </dev/null`
         echo "pid running on dbport: $opid"
     fi
-    $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node:$dbport ${LCLDBNAME} 'select comdb2_dbname()' 2>&1
+    $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node:$dbport $DBNAME 'select comdb2_dbname()' 2>&1
 }
 
 
 # test largecsc2 throws error about col width
-#if grep "ERROR" $LOGDIR/${LCLDBNAME}.init | grep -v largecsc2 ; then
-#    echo "Error while initializing DB, see $LOGDIR/${LCLDBNAME}.init "
+#if grep "ERROR" $LOGDIR/${DBNAME}.init | grep -v largecsc2 ; then
+#    echo "Error while initializing DB, see $LOGDIR/${DBNAME}.init "
 #    exit 1
 #fi
 
@@ -259,19 +252,19 @@ check_db_port_running_node() {
 if [[ -z "$CLUSTER" ]]; then
 
     if [[ -n ${DEBUG_PREFIX} && ${INTERACTIVE_DEBUG} -eq 1 ]]; then
-        echo -e "!$TESTCASE: Execute the following command in a separate terminal: ${TEXTCOLOR}cd $LCLDBDIR && ${DEBUG_PREFIX} $COMDB2_EXE $PARAMS --pidfile ${TMPDIR}/${LCLDBNAME}.pid${NOCOLOR}"
+        echo -e "!$TESTCASE: Execute the following command in a separate terminal: ${TEXTCOLOR}cd $DBDIR && ${DEBUG_PREFIX} $COMDB2_EXE $PARAMS --pidfile ${TMPDIR}/$DBNAME.pid${NOCOLOR}"
         exit 0
     fi
 
     echo "!$TESTCASE: starting single node"
-    ${DEBUG_PREFIX} $COMDB2_EXE $PARAMS --pidfile ${TMPDIR}/${LCLDBNAME}.pid &> $LOGDIR/${LCLDBNAME}.db &
+    ${DEBUG_PREFIX} $COMDB2_EXE $PARAMS --pidfile ${TMPDIR}/${DBNAME}.pid &> $LOGDIR/${DBNAME}.db &
     dbpid=$!
 
     set +e
 
-    kill -0 `cat ${TMPDIR}/${LCLDBNAME}.pid` > /dev/null
+    kill -0 `cat ${TMPDIR}/${DBNAME}.pid` > /dev/null
     if [ $? -eq 1 ] ; then
-        echo "pid ${TMPDIR}/${LCLDBNAME}.pid: `cat ${TMPDIR}/${LCLDBNAME}.pid` is not alive"
+        echo "pid ${TMPDIR}/${DBNAME}.pid: `cat ${TMPDIR}/${DBNAME}.pid` is not alive"
         check_db_port_running_local # this error is immediate so we should be able to catch it early
     fi
 
@@ -280,8 +273,8 @@ if [[ -z "$CLUSTER" ]]; then
     echo "!$TESTCASE: waiting until ready"
     while [[ "$out" != "1" ]]; do
         sleep 1
-        out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs ${LCLDBNAME} default 'select 1' 2> /dev/null)
-        $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs ${LCLDBNAME} 'select 1' &> $LOGDIR/${LCLDBNAME}.conn
+        out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs $DBNAME default 'select 1' 2> /dev/null)
+        $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs $DBNAME 'select 1' &> $LOGDIR/${DBNAME}.conn
     done
 else
     echo "!$TESTCASE: copying to cluster"
@@ -291,8 +284,8 @@ else
     COMDB2AR_AROPTS="-C preserve"
     COMDB2AR_EXOPTS="-x $COMDB2_EXE"
 
-    ARFILE=$LCLDBDIR/${LCLDBNAME}.ar
-    $COMDB2AR_EXE $COMDB2AR_AROPTS c ${LRL} 2> $LOGDIR/${LCLDBNAME}.arstatus > $ARFILE
+    ARFILE=$DBDIR/${DBNAME}.ar
+    $COMDB2AR_EXE $COMDB2AR_AROPTS c ${LRL} 2> $LOGDIR/${DBNAME}.arstatus > $ARFILE
     [ ! -f $ARFILE ] && echo "failed to create $ARFILE" && exit 1
 
     i=0
@@ -301,7 +294,7 @@ else
         if [ $node == $HOSTNAME ] ; then
             continue
         fi
-        cat $ARFILE | ssh $SSH_OPT $node "cd ${LCLDBDIR}; $COMDB2AR_EXE $COMDB2AR_EXOPTS $COMDB2AR_AROPTS -u 95 x $LCLDBDIR" &> $LOGDIR/${LCLDBNAME}.${node}.copy &
+        cat $ARFILE | ssh $SSH_OPT $node "cd ${DBDIR}; $COMDB2AR_EXE $COMDB2AR_EXOPTS $COMDB2AR_AROPTS -u 95 x $DBDIR" &> $LOGDIR/${DBNAME}.${node}.copy &
         pids[$i]=$!
         let i=i+1
     done
@@ -312,21 +305,21 @@ else
         fi
         wait ${pids[$i]}
         if [[ $? -ne 0 ]]; then
-            echo "FAILED: copying ${LRL} ${node}: see $LOGDIR/${LCLDBNAME}.${node}.copy"
+            echo "FAILED: copying ${LRL} ${node}: see $LOGDIR/${DBNAME}.${node}.copy"
             exit 1
         fi
         let i=i+1
     done
 
     echo "export COMDB2_ROOT=$COMDB2_ROOT" >> ${TESTDIR}/replicant_vars
-    CMD="cd ${LCLDBDIR}; source ${TESTDIR}/replicant_vars ; ${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} --pidfile ${TMPDIR}/${LCLDBNAME}.pid 2>&1 | tee $TESTDIR/${LCLDBNAME}.db"
+    CMD="cd ${DBDIR}; source ${TESTDIR}/replicant_vars ; ${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} --pidfile ${TMPDIR}/$DBNAME.pid 2>&1 | tee $TESTDIR/${DBNAME}.db"
     echo "!$TESTCASE: starting"
     for node in $CLUSTER; do
         if [ $node == $HOSTNAME ] ; then # dont ssh to ourself -- just start db locally
             if [[ -n ${DEBUG_PREFIX} && ${INTERACTIVE_DEBUG} -eq 1 ]]; then
-                echo -e "!$TESTCASE: Execute the following command on ${node}: ${TEXTCOLOR}${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} --pidfile ${TMPDIR}/${LCLDBNAME}.${node}.pid${NOCOLOR}"
+                echo -e "!$TESTCASE: Execute the following command on ${node}: ${TEXTCOLOR}${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} --pidfile ${TMPDIR}/${DBNAME}.${node}.pid${NOCOLOR}"
             else
-                ${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} --pidfile ${TMPDIR}/${LCLDBNAME}.${node}.pid &> $LOGDIR/${LCLDBNAME}.${node}.db &
+                ${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} --pidfile ${TMPDIR}/${DBNAME}.${node}.pid &> $LOGDIR/${DBNAME}.${node}.db &
             fi
             continue
         fi
@@ -337,9 +330,9 @@ else
             scp $SSH_OPT ${TESTDIR}/replicant_vars $node:${TESTDIR}/replicant_vars
             # redirect output from CMD to a subshell which runs awk to prepend time
             # could also use connection sharing and close master ssh session in unsetup
-            ssh -n $SSH_OPT -tt $node ${CMD} &>$LOGDIR/${LCLDBNAME}.${node}.db &
+            ssh -n $SSH_OPT -tt $node ${CMD} &>$LOGDIR/${DBNAME}.${node}.db &
             # $! will be pid of ssh (if we had used pipe, $! would be pid of awk)
-            echo $! > ${TMPDIR}/${LCLDBNAME}.${node}.pid
+            echo $! > ${TMPDIR}/${DBNAME}.${node}.pid
         fi
     done
 
@@ -347,9 +340,9 @@ else
     #check for failure in starting any of the nodes
     sleep 1
     for node in $CLUSTER; do
-        kill -0 `cat ${TMPDIR}/${LCLDBNAME}.${node}.pid` > /dev/null
+        kill -0 `cat ${TMPDIR}/${DBNAME}.${node}.pid` > /dev/null
         if [ $? -eq 1 ] ; then
-            echo "pid ${TMPDIR}/${LCLDBNAME}.${node}.pid: `cat ${TMPDIR}/${LCLDBNAME}.${node}.pid` is not alive"
+            echo "pid ${TMPDIR}/${DBNAME}.${node}.pid: `cat ${TMPDIR}/${DBNAME}.${node}.pid` is not alive"
             check_db_port_running_node $node # this error is immediate so we should be able to catch it early
         fi
     done
@@ -357,22 +350,22 @@ else
     echo "!$TESTCASE: waiting until ready"
     for node in $CLUSTER; do
         echo "If we can't talk to any of the nodes the test will timeout"
-        out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node ${LCLDBNAME} 'select 1' 2>&1)
+        out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
         while  [[ "$out" != "1" ]]; do
             sleep 2
-            out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node ${LCLDBNAME} 'select 1' 2>&1)
-            $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs --host $node ${LCLDBNAME} 'select 1' &> $LOGDIR/${LCLDBNAME}.${node}.conn
+            out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
+            $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' &> $LOGDIR/${DBNAME}.${node}.conn
         done
-        $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs --host $node ${LCLDBNAME} 'select comdb2_host()' &>> $LOGDIR/${LCLDBNAME}.${node}.conn
-        out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node ${LCLDBNAME} 'select comdb2_host()' 2>&1)
+        $CDB2SQL_EXE -v ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select comdb2_host()' &>> $LOGDIR/${DBNAME}.${node}.conn
+        out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select comdb2_host()' 2>&1)
         if [ "$out" != "$node" ] ; then
             sleep 1
             failexit "comdb2_host() '$out' != expected '$node'"
         fi
     done
     for node in $CLUSTER; do
-        $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs ${LCLDBNAME} --host $node 'exec procedure sys.cmd.send("udp stat all")'
-        $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs ${LCLDBNAME} --host $node 'exec procedure sys.cmd.send("udp ping all")'
+        $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs $DBNAME --host $node 'exec procedure sys.cmd.send("udp stat all")'
+        $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs $DBNAME --host $node 'exec procedure sys.cmd.send("udp ping all")'
     done
 fi
 
