ar file in dbdir, local variables, fix total test counter

diff --git a/tests/setup b/tests/setup
--- a/tests/setup
+++ b/tests/setup
@@ -197,24 +197,25 @@ echo "${DBNAME} created successfully"
 set -e
 
 check_db_port_running_local() {
-    dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
+    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
     if [ "x$dbport" == "x" ] ; then
         return
     fi
     echo "checking what is running on localhost:$dbport"
     netstat -na | grep $dbport
-    opid=`fuser -n tcp $dbport`
+    local opid=`fuser -n tcp $dbport`
     echo "pid running on dbport: $opid"
     [ -n "$opid" ] && ps -p $opid -o comm,args
     $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host localhost:$dbport $DBNAME 'select comdb2_dbname()' 2>&1
 }
 
 check_db_port_running_node() {
-    node=$1
-    dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.${node}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
+    local node=$1
+    local dbport=`grep "\[ERROR\] net_listen: FAILED TO BIND to port" $TESTDIR/logs/${DBNAME}.${node}.db | grep -Po "port [0-9]*" | cut -f2 -d" " `
     if [ "x$dbport" == "x" ] ; then
         return;
     fi
+    local opid
     echo "checking what is running on ${node}:$dbport"
     if [ "$node" == "$HOSTNAME" ] ; then 
         netstat -na | grep $dbport
@@ -266,13 +267,14 @@ else
     COMDB2AR_AROPTS="-C preserve"
     COMDB2AR_EXOPTS="-x $COMDB2_EXE"
 
-    $COMDB2AR_EXE $COMDB2AR_AROPTS c ${LRL} 2> $TESTDIR/logs/${DBNAME}.arstatus > $TESTDIR/${DBNAME}.ar
-    [ ! -f $TESTDIR/${DBNAME}.ar ] && echo "failed to create $TESTDIR/${DBNAME}.ar" && exit 1
+    ARFILE=$DBDIR/${DBNAME}.ar
+    $COMDB2AR_EXE $COMDB2AR_AROPTS c ${LRL} 2> $TESTDIR/logs/${DBNAME}.arstatus > $ARFILE
+    [ ! -f $ARFILE ] && echo "failed to create $ARFILE" && exit 1
 
     i=0
     declare -a pids
     for node in ${CLUSTER/$HOSTNAME/}; do
-        cat $TESTDIR/${DBNAME}.ar | ssh $SSH_OPT $node "$COMDB2AR_EXE $COMDB2AR_EXOPTS $COMDB2AR_AROPTS -u 95 x $DBDIR" &> $TESTDIR/logs/${DBNAME}.${node}.copy &
+        cat $ARFILE | ssh $SSH_OPT $node "$COMDB2AR_EXE $COMDB2AR_EXOPTS $COMDB2AR_AROPTS -u 95 x $DBDIR" &> $TESTDIR/logs/${DBNAME}.${node}.copy &
         pids[$i]=$!
         let i=i+1
     done
