fix and cleanup tests (#228, AZ_fix_tests)
* dont accumulate tons of longreqs for sirace test
* add type intervaldsus to alltypes test in comdb2sys
* add type intervaldsus to alltypes test in comdb2sys
* remove bad lrl setting sc_logical_txn from few tests
* move keywords test into more appropriate comdb2sys test
* remove bad attr MAX_SHADOW_ROWS from tests
* delete bad lrl option enable_true_serializable from tests
* downgrade to warn logmsg set gbl_recoverable_lsn
* new_snapshot is not a valid option
* delete extra files, correct name of setting for parenttran_fail
* remove bad lrl options for keycompr
* unneeded option for test snap_ha_retry

diff --git a/tests/setup b/tests/setup
--- a/tests/setup
+++ b/tests/setup
@@ -201,8 +201,16 @@ $comdb2task --create --lrl $DBDIR/${DBNAME}.lrl --pidfile ${TMPDIR}/$DBNAME.pid 
 rc=$?
 rm -f ${DBNAME}.trap
 if [[ $rc -ne 0 ]]; then
+    echo "Error rc=$rc while initializing DB, see $TESTDIR/logs/${DBNAME}.init "
     exit 1
 fi
+
+# test largecsc2 throws error about col width, can't enable this by default
+#if grep "ERROR" $TESTDIR/logs/${DBNAME}.init ; then
+#    echo "Error while initializing DB, see $TESTDIR/logs/${DBNAME}.init "
+#    exit 1
+#fi
+
 
 # start it
 cd $DBDIR >/dev/null
