cdb2sql: tabluar display mode

diff --git a/tests/cdb2sql.test/runit b/tests/cdb2sql.test/runit
--- a/tests/cdb2sql.test/runit
+++ b/tests/cdb2sql.test/runit
@@ -7,7 +7,7 @@ if [[ -z $dbname ]] ; then
     exit 1
 fi
 
-for testreq in `ls t*.sql` ; do
+for testreq in `find . -name 't[0-9][0-9].sql'` ; do
     testname=`echo $testreq | cut -d "." -f 1`
     cmd="cdb2sql -s -f $testreq ${CDB2_OPTIONS} $dbname default "
     echo $cmd "> $testname.output"
@@ -26,5 +26,26 @@ for testreq in `ls t*.sql` ; do
         exit 1
     fi
 done
+
+for testreq in `find . -name 't[0-9][0-9].tab.sql'` ; do
+    testname=`echo $testreq | cut -d "." -f 1`
+    cmd="cdb2sql -s -f $testreq ${CDB2_OPTIONS} -tabular $dbname default "
+    echo $cmd "> $testname.output"
+    $cmd 2>&1 | perl -pe "s/.n_writeops_done=([0-9]+)/rows inserted='\1'/; s/BLOCK2_SEQV2\(824\)/BLOCK_SEQ(800)/; s/OP #2 BLOCK_SEQ/OP #3 BLOCK_SEQ/;" > $testname.output
+
+    cmd="diff $testname.expected $testname.output"
+    $cmd > /dev/null
+
+    if [[  $? -eq 0 ]]; then
+        echo "passed $testname"
+    else
+        echo "failed $testname"
+        echo "see diffs here: $HOSTNAME"
+        echo "> diff -u ${PWD}/{$testname.tab.expected,$testname.output}"
+        echo
+        exit 1
+    fi
+done
+
 echo
 exit 0
