clustered test

diff --git a/tests/copyschema_timepart.test/runit b/tests/copyschema_timepart.test/runit
--- a/tests/copyschema_timepart.test/runit
+++ b/tests/copyschema_timepart.test/runit
@@ -4,7 +4,6 @@ bash -n "$0" | exit 1
 # Time partition testcase for comdb2
 ################################################################################
 
-
 # args
 # <dbname>
 dbname=$1
@@ -44,6 +43,36 @@ function timepart_stats
         exit 1
     fi
 }
+
+function timepart_stats2
+{
+    dbn=$1
+    nd=$2
+    # check the current partitions 
+    echo $CDB2SQL_EXE -tabs --host $nd $dbn default "exec procedure sys.cmd.send('partitions')" | 
+        egrep -v "STARTTIME|LOW|HIGH|SOURCE_ID"
+    $CDB2SQL_EXE -tabs --host $nd $dbn default "exec procedure sys.cmd.send('partitions')" |
+        egrep -v "STARTTIME|LOW|HIGH|SOURCE_ID" >> $OUT
+    if (( $? != 0 )) ; then
+        echo "FAILURE"
+        exit 1
+    fi
+
+    echo $CDB2SQL_EXE --host $nd $dbn default  "select name, period, retention, nshards, version,shard0name from comdb2_timepartitions "
+    $CDB2SQL_EXE --host $nd $dbn default  "select name, period, retention, nshards, version,shard0name from comdb2_timepartitions " >> $OUT
+    if (( $? != 0 )) ; then
+        echo "FAILURE"
+        exit 1
+    fi
+
+    echo $CDB2SQL_EXE --host $nd $dbn default  "select name, shardname from comdb2_timepartshards"
+    $CDB2SQL_EXE --host $nd $dbn default  "select name, shardname from comdb2_timepartshards" >> $OUT
+    if (( $? != 0 )) ; then
+        echo "FAILURE"
+        exit 1
+    fi
+}
+
 
 timepart_stats $dbname
 
@@ -111,78 +140,68 @@ fi
 
 timepart_stats $dbname
 
+cp clonedb.sh clonedb.sh.actual
+sed -i "s~\$dbname~$dbname~g" clonedb.sh.actual
+sed -i "s~\$TESTDIR~$TESTDIR~g" clonedb.sh.actual
+sed -i "s~\$DBDIR~$DBDIR~g" clonedb.sh.actual
+sed -i "s~\$TMPDIR~$TMPDIR~g" clonedb.sh.actual
+sed -i "s~\$COMDB2_EXE~$COMDB2_EXE~g" clonedb.sh.actual
+sed -i "s~\$COMDB2AR_EXE~$COMDB2AR_EXE~g" clonedb.sh.actual
 
-# create a temporary directory
 newdb=srcdb$dbname
 newdbdir=$TESTDIR/$newdb
 newlrl=$newdbdir/$newdb.lrl
 
-echo "Creating newdb $dbname in $newdbdir"
+if [ -z $CLUSTER ]; then
+    ./clonedb.sh.actual
 
-# copy the schema of the old db
-echo $COMDB2AR_EXE -s c $DBDIR/$dbname.lrl | $COMDB2AR_EXE  -C preserve -u 95 x $newdbdir $newdbdir
-$COMDB2AR_EXE -s c $DBDIR/$dbname.lrl | $COMDB2AR_EXE  -C preserve -u 95 x $newdbdir $newdbdir
-echo mv $newdbdir/$dbname.lrl $newlrl
-mv $newdbdir/$dbname.lrl $newlrl
-echo sed -i "/^name /s/$dbname/$newdb/g" $newlrl
-sed -i "/^name /s/$dbname/$newdb/g" $newlrl
+    echo "Bringing the $newdb up"
 
-# recreate the db
-echo $COMDB2_EXE $newdb --create --lrl $newlrl
-$COMDB2_EXE $newdb --create --lrl $newlrl
-if (( $? != 0 )) ; then
-   echo "FAILURE"
-   exit 1
-fi
-
-echo "Bringing the $newdb up"
-
-# bring the db up
-echo $COMDB2_EXE $newdb --lrl $newlrl --pidfile ${TMPDIR}/$newdb.pid
-$COMDB2_EXE $newdb --lrl $newlrl --pidfile ${TMPDIR}/$newdb.pid &
-if (( $? != 0 )) ; then
-   echo "FAILURE"
-   exit 1
-fi
-
-echo "Waiting for db"
-
-sleep 20
-
-echo "Confirming time partition transfer for $newdb"
-
-# double check the time partition settings
-timepart_stats $newdb
-
-echo "Killing the $newdb"
-
-# bring down new db
-kill_by_pidfile() {
-    local pidfile=$1
-    if [[ -f $pidfile ]]; then
-        local pid=$(cat $pidfile)
-        local pstr=$(ps -p $pid -o args | grep comdb2)
-        echo $pstr | grep -q "comdb2 ${newdb}"
-        if [[ $? -eq 0 ]]; then
-            echo "${TESTCASE}: killing $pid"
-            if [ "`echo $pstr | awk '{ print $1 }' | xargs basename`" = "comdb2" ] ; then
-                kill -9 $pid
-            else
-                kill $pid
-            fi
-        fi
-        rm -f $pidfile
-    else
-        echo "kill_by_pidfile: pidfile $pidfile does not exist"
+    # bring the db up
+    echo $COMDB2_EXE $newdb --lrl $newlrl --pidfile $TMPDIR/$newdb.pid
+    $COMDB2_EXE $newdb --lrl $newlrl --pidfile $TMPDIR/$newdb.pid &
+    if (( $? != 0 )) ; then
+        echo "FAILURE"
+        exit 1
     fi
-}
-kill_by_pidfile ${TMPDIR}/$newdb.pid 
 
+    echo "Waiting for db"
+    sleep 10
 
+    echo "Confirming time partition transfer for $newdb"
+    timepart_stats2 $newdb `hostname`
+
+    echo "Killing db $newdb"
+    ./killdb.sh $newdb ${TMPDIR}/$newdb.pid
+else
+    node=`echo $CLUSTER | awk '{ print $1}'`
+    scp clonedb.sh.actual $node:$DBDIR/clonedb.sh.actual
+    scp killdb.sh $node:$DBDIR/killdb.sh
+
+    ssh $node $DBDIR/clonedb.sh.actual
+
+    echo "Bringing the $newdb up"
+
+    # bring the db up
+    echo nohup $COMDB2_EXE $newdb --lrl $newlrl --pidfile $TMPDIR/$newdb.pid
+    ssh $node nohup $COMDB2_EXE $newdb --lrl $newlrl --pidfile $TMPDIR/$newdb.pid &
+    if (( $? != 0 )) ; then
+        echo "FAILURE"
+        exit 1
+    fi
+
+    echo "Waiting for db"
+    sleep 10
+
+    echo "Confirming time partition transfer for $newdb"
+    timepart_stats2 $newdb $node
+
+    echo "Killing db $newdb"
+    ssh $node $DBDIR/killdb.sh $newdb  ${TMPDIR}/$newdb.pid
+fi
 
 # we need to scrub dbname from alpha
 sed "s/dorintdb/$dbname/g; s#\${CDB2_OPTIONS}#${CDB2_OPTIONS}#g" $OUT.alpha > $OUT.alpha.actual
-
 
 difs=`diff $OUT $OUT.alpha.actual`
 if [[ ! -z "${difs}" ]] ; then
