Showing shard disk size in comdb2_timepartshards
This patch adds a `size' column to the `comdb2_timepartshards' system table.
The value of the new column is the shard's disk size in bytes.

Signed-off-by: Rivers Zhang <hzhang320@bloomberg.net>

diff --git a/tests/simple_timepart.test/runit b/tests/simple_timepart.test/runit
--- a/tests/simple_timepart.test/runit
+++ b/tests/simple_timepart.test/runit
@@ -36,6 +36,12 @@ function timepart_stats
         exit 1
     fi
 
+    cdb2sql ${CDB2_OPTIONS} $dbname default  "select shardname, size from comdb2_timepartshards"
+    if (( $? != 0 )) ; then
+        echo "FAILURE"
+        exit 1
+    fi
+
     echo cdb2sql ${CDB2_OPTIONS} $dbname default  "select name, shardname from comdb2_timepartshards" >> $OUT
     cdb2sql ${CDB2_OPTIONS} $dbname default  "select name, shardname from comdb2_timepartshards" >> $OUT
     if (( $? != 0 )) ; then
