systable for time partition events and test

diff --git a/tests/simple_timepart.test/runit b/tests/simple_timepart.test/runit
--- a/tests/simple_timepart.test/runit
+++ b/tests/simple_timepart.test/runit
@@ -40,6 +40,13 @@ function timepart_stats
         echo "FAILURE"
         exit 1
     fi
+
+    echo cdb2sql ${CDB2_OPTIONS} $dbname default  "select name, arg1, arg2, arg3 from comdb2_timepartevents" >> $OUT
+    cdb2sql ${CDB2_OPTIONS} $dbname default  "select name, arg1, arg2, arg3 from comdb2_timepartevents" >> $OUT
+    if (( $? != 0 )) ; then
+        echo "FAILURE"
+        exit 1
+    fi
 }
 
 timepart_stats
