push to work on train

diff --git a/tests/sc_truncate.test/runit b/tests/sc_truncate.test/runit
--- a/tests/sc_truncate.test/runit
+++ b/tests/sc_truncate.test/runit
@@ -8,31 +8,11 @@ bash -n "$0" | exit 1
 . ${TESTSROOTDIR}/tools/ddl.sh
 . ${TESTSROOTDIR}/tools/cluster_utils.sh
 
-function cleanup
-{
-    [[ $debug == "1" ]] && set -x
-    typeset func="cleanup"
-    write_prompt $func "Running $func"
-    touch $stopfile
-    wait
-}
-
 function randomtable
 {
     [[ $debug == "1" ]] && set -x
     typeset table=$(( RANDOM % tablecount ))
     echo "t$table"
-}
-
-function failexit
-{
-    [[ $debug == "1" ]] && set -x
-    typeset func="failexit"
-    write_prompt $func "Running $func"
-    typeset f=$1
-    write_prompt $func "$f failed: $2"
-    cleanup
-    exit -1
 }
 
 function create_database_tables
@@ -59,11 +39,22 @@ function truncate_thread
     [[ $debug == "1" ]] && set -x
     typeset func="truncate_thread"
     typeset tdno=$1
-    typeset sleep_sec=${2:-0.10}
+    typeset sleep_sec=${2}
+    typeset max_fail=${3}
+    typeset curfail=0
     write_prompt $func "Running $func $tdno"
     while [[ ! -f $stopfile ]]; do
         table=$(randomtable)
-        truncate_table $table
+        out=$(truncate_table $table)
+        echo "$out"
+        if [[ $out = *fail* ]]; then
+            let curfail=curfail+1
+            if [[ $curfail -gt $max_fail ]]; then
+                echo "Too many truncate failures: $curfail" >> $failfile
+            fi
+        else
+            curfail=0
+        fi
         [[ $sleep_sec ]] && sleep $sleep_sec
     done
 }
@@ -100,6 +91,7 @@ function run_test
     typeset insertrecs=${5}
     typeset nocheckpoint=${6}
     typeset dgcount=${7}
+    typeset maxtruncatefail=${8}
 
     # Locals
     typeset maxtime=300
@@ -111,6 +103,7 @@ function run_test
 
     create_database_tables
     rm -f $stopfile
+    rm -f $failfile
 
     # Tell nodes to not change the checkpoint-lsn
     if [[ $nocheckpoint != 0 ]]; then
@@ -121,7 +114,7 @@ function run_test
 
     i=0
     while [[ $i -lt $truncaters ]]; do
-        truncate_thread $i $truncate_sleep &
+        truncate_thread $i $truncate_sleep $maxtruncatefail &
         let i=i+1
     done
 
@@ -148,6 +141,8 @@ function run_test
 
 # Globals
 export stopfile=./stop.test
+export failfile=./failed.test
+
 if [[ $DBNAME == *"lockordergenerated"* ]]; then
     export tablecount=3
     export truncaters=5
@@ -157,6 +152,7 @@ if [[ $DBNAME == *"lockordergenerated"* ]]; then
     export insertrecs=10
     export nocheckpoint=0
     export dgcount=0
+    export maxtruncatefail=10
 else
     export tablecount=100
     export truncaters=1
@@ -166,8 +162,14 @@ else
     export insertrecs=10000
     export nocheckpoint=1
     export dgcount=0
+    export maxtruncatefail=10
 fi
 
-run_test $truncaters $truncate_sleep $downgrade_sleep $inserters $insertrecs $nocheckpoint $dgcount
+run_test $truncaters $truncate_sleep $downgrade_sleep $inserters $insertrecs $nocheckpoint $dgcount $maxtruncatefail
+if [[ -f $failfile ]]; then
+    echo "Failed test"
+    cat $failfile
+    exit 1
+fi
 
 echo "Success"
