Bug in physical replicant attempting to write logs.

diff --git a/tests/phys_rep.test/runit b/tests/phys_rep.test/runit
--- a/tests/phys_rep.test/runit
+++ b/tests/phys_rep.test/runit
@@ -3,8 +3,8 @@
 
 env
 dbname=$1
-NRECS=1000
-NRUNS=10000
+NRECS=10
+NRUNS=100
 
 set -x
 
@@ -22,6 +22,7 @@ if [ -n "$PMUXPORT" ] ; then
     echo "portmux_port $PMUXPORT" >> $DEST_DBDIR/${destdb}.lrl
     echo "portmux_bind_path $pmux_socket" >> $DEST_DBDIR/${destdb}.lrl
 fi
+comdb2 $destdb -lrl $DEST_DBDIR/${destdb}.lrl -pidfile $DEST_DBDIR/${destdb}.pid &
 
 out=
 while [[ "$out" != "1" ]]; do
@@ -29,12 +30,49 @@ while [[ "$out" != "1" ]]; do
     sleep 1
 done
 
+# requires $1 and $2
+equal_queries() {
+    lhs="$1" 
+    rhs="$2"
+
+    [ "$lhs" = "$rhs" ]
+}
+
+failure() {
+    kill -9 $(cat $DEST_DBDIR/${destdb}.pid)
+}
+
+# generate our tests that we will use
+set +x
+source ./generate_tests.sh
+set -x
+
 # iterate over each test
-for sql in `ls *.sql | sort -V`; do
-    src=$(cdb2sql -s --tabs -f $sql ${CDB2_OPTIONS} $dbnme default 2>&1) 
-    dest=$(cdb2sql -s --tabs -f $sql ${CDB2_OPTIONS} $destdb localhost 2>&1)
-    if [ "$?" != "0" ]; then
-        echo 'Failed.'
+for sql in `ls *.src.sql | sort -V`; do
+    $(cdb2sql -s --tabs -f $sql ${CDB2_OPTIONS} $dbname default 2>&1 > /dev/null) 
+    query_cmd=$(echo $sql | sed 's/\.src\.sql//').query.sql
+
+    src=$(cdb2sql -s --tabs -f $query_cmd ${CDB2_OPTIONS} $dbname default 2>&1 | md5sum) 
+    dest=$(cdb2sql -s --tabs -f $query_cmd ${CDB2_OPTIONS} $destdb local 2>&1 | md5sum)
+
+    failed=1
+    for i in `seq 1 5`;
+    do
+        if ! $(equal_queries "$src" "$dest"); then
+            echo 'Replicant not updated'
+            sleep 1
+            src=$(cdb2sql -s --tabs -f $query_cmd ${CDB2_OPTIONS} $dbname default 2>&1 | md5sum) 
+            dest=$(cdb2sql -s --tabs -f $query_cmd ${CDB2_OPTIONS} $destdb local 2>&1 | md5sum)
+            continue
+        fi
+        
+        failed=0
+        break
+    done
+
+    if ! [ $failed -eq 0 ]; then
+        echo "Failed on $sql test."
+        $(failure)
         exit 1
     fi
 done
@@ -98,14 +136,7 @@ echo "src2 $src2 dest2 $dest2"
 # echo deregister from pmux ${destdb}
 # ${TESTSROOTDIR}/tools/send_msg_port.sh "del comdb2/replication/${destdb} " ${pmux_port}
 
-if [[ "$src" != "$dest" ]]; then
-    exit 1
-fi
-
-if [[ "$src2" != "$dest2" ]]; then
-    echo "truncate failed"
-    exit 1
-fi
+kill -9 $(cat $DEST_DBDIR/${destdb}.pid)
 
 exit 0
 xit 0
