error message can be different on bb machines

diff --git a/tests/dbcreate.test/runit b/tests/dbcreate.test/runit
--- a/tests/dbcreate.test/runit
+++ b/tests/dbcreate.test/runit
@@ -30,10 +30,10 @@ grep "lrl : No such file or directory" out || failexit "expected 'No such file o
 
 echo "Check 2"
 mkdir -p $TSTDBDIR
-touch $TSTDBDIR/${DB}.lrl
+echo "logmsg level debug" > $TSTDBDIR/${DB}.lrl
 #should not crash
 ${COMDB2_EXE} --no-global-lrl --create $DB --lrl $TSTDBDIR/${DB}.lrl &> out
-grep "\[FATAL\] failed to open bdb_env for " out || failexit "expected '[FATAL] failed to open bdb_env for '"
+grep "\[FATAL\] failed to open bdb_env for \| \[FATAL\] DB directory" out || failexit "expected '[FATAL] failed to open bdb_env for ' or '\[FATAL\] DB directory'"
 
 echo "Check 3"
 ${COMDB2_EXE} --no-global-lrl $DB --lrl $TSTDBDIR/${DB}.lrl &> out
