Bring up cdb2sockpool if not running.

diff --git a/tests/nowritetimeout.test/runit b/tests/nowritetimeout.test/runit
--- a/tests/nowritetimeout.test/runit
+++ b/tests/nowritetimeout.test/runit
@@ -6,6 +6,16 @@ dbnm=$1
 pgrep cdb2sockpool
 if [ $? -ne 0 ]; then
     echo 'SOCKPOOL IS REQUIRED TO RUN THE TEST.' >&2
-    exit 1
+    echo 'TRY TO BRING UP SOCKPOOL'
+    ${BUILDDIR}/tools/cdb2sockpool/cdb2sockpool
+    sleep 1
+    pgrep cdb2sockpool
+    if [ $? -ne 0 ]; then
+        echo 'FAILED THE ATTEMPT.' >&2
+        exit 1
+    fi
 fi
 ${TESTSBUILDDIR}/nowritetimeout $dbnm
+rc=$?
+pkill cdb2sockpool
+exit $rc
