integrate makecluster in test setup

diff --git a/contrib/comdb2makecluster/comdb2makecluster b/contrib/comdb2makecluster/comdb2makecluster
--- a/contrib/comdb2makecluster/comdb2makecluster
+++ b/contrib/comdb2makecluster/comdb2makecluster
@@ -23,6 +23,13 @@ if [[ $# -lt 3 || $1 = "--help" || $1 = "-h" ]] ; then
     usage
 fi
 
+CREATEDB=1
+if [[ $1 = "--nocreate" ]] ; then 
+    shift
+    CREATEDB=0
+fi
+
+
 if [[ $1 = "--dir" ]] ; then 
     shift
     DBDIR=$1
@@ -55,110 +62,106 @@ fi
 TMPDIR=${TMPDIR:-/tmp}
 CDB2_CONFIG=$DBDIR/comdb2db.cfg
 CDB2_OPTIONS="--cdb2cfg ${CDB2_CONFIG}"
-COMDB2_EXE=comdb2
-COMDB2AR_EXE=comdb2ar
+COMDB2_EXE=${COMDB2_EXE:-comdb2}
+CDB2SQL_EXE=${CDB2SQL_EXE:-cdb2sql}
+COMDB2AR_EXE=${COMDB2AR_EXE:-comdb2ar}
+COPYCOMDB2_EXE=${COPYCOMDB2_EXE:-copycomdb2}
 export comdb2ar=$COMDB2AR_EXE  # used by copycomdb2
 export COMDB2AR_EXOPTS="-x $COMDB2_EXE"
 export COMDB2_ROOT=${DBDIR}
 myhostname=`hostname`
+LOGDIR=${LOGDIR:-$DBDIR/var/log}
+
 
 check_executables_for_cluster() 
 {
+    which $COMDB2AR_EXE  > /dev/null || failexit "$COMDB2AR_EXE not in path"
+    which $COPYCOMDB2_EXE  > /dev/null || failexit "$COPYCOMDB2_EXE not in path"
     for node in $CLUSTER; do
         if [ $node == $myhostname ] ; then
-            ls $DBDIR &> /dev/null && failexit "$DBDIR already exists, please clean up before attempting to start"
+            if [ $CREATE == 1 ] ; then
+                ls $DBDIR &> /dev/null && failexit "$DBDIR already exists, please clean up before attempting to start"
+            fi
             which $COMDB2_EXE > /dev/null || failexit "$COMDB2_EXE not in path"
-            which $COMDB2AR_EXE  > /dev/null || failexit "$COMDB2AR_EXE not in path"
-            which copycomdb2  > /dev/null || failexit "copycomdb2 not in path"
             continue
         fi
 
-        ssh -o StrictHostKeyChecking=no $node "ls $DBDIR > /dev/null 2>&1" < /dev/null && failexit "$DBDIR already exists in node $node, please clean up before attempting to start"
-        ssh -o StrictHostKeyChecking=no $node "which $COMDB2_EXE > /dev/null 2>&1" < /dev/null || failexit "$COMDB2_EXE not in path in node $node"
-        ssh -o StrictHostKeyChecking=no $node "which $COMDB2AR_EXE > /dev/null 2>&1" < /dev/null || failexit "$COMDB2AR_EXE not in path in node $node"
+        hst=$(ssh -o StrictHostKeyChecking=no $node "hostname" < /dev/null )
+        if [ "x$hst" == "x" ] ; then
+            failexit "cant get hostname on $node"
+        fi
+
+        ssh -o StrictHostKeyChecking=no $node "ls $DBDIR > /dev/null 2>&1" < /dev/null && failexit "$DBDIR already exists in node $node, please clean up before attempting to start" < /dev/null
+        ssh -o StrictHostKeyChecking=no $node "which $COMDB2_EXE > /dev/null 2>&1" < /dev/null || failexit "$COMDB2_EXE not in path in node $node" < /dev/null
+        ssh -o StrictHostKeyChecking=no $node "which $COMDB2AR_EXE > /dev/null 2>&1" < /dev/null || failexit "$COMDB2AR_EXE not in path in node $node" < /dev/null
     done
 }
 
 check_executables_for_cluster
 
-
-mkdir -p $DBDIR $TMPDIR
-mkdir -p $DBDIR/logs $DBDIR/var/log/cdb2 $DBDIR/tmp/cdb2
-
-# setup files:
-echo "$DBNAME: creating"
 LRL="$DBDIR/$DBNAME.lrl"
-> ${LRL}
+PARAMS="$DBNAME --no-global-lrl"
+if [ $CREATEDB == 1 ] ; then 
+    mkdir -p $DBDIR $TMPDIR
+    mkdir -p $LOGDIR $DBDIR/var/log/cdb2 $DBDIR/tmp/cdb2
 
-cat >> $DBDIR/$DBNAME.lrl <<EOPTIONS
+    # setup files:
+    echo "$DBNAME: creating"
+    > ${LRL}
+
+    cat >> $DBDIR/$DBNAME.lrl <<EOPTIONS
 name    $DBNAME
 dir     $DBDIR
 
 EOPTIONS
 
-df $DBDIR | awk '{print $1 }' | grep "tmpfs\|nfs" > /dev/null && echo "setattr directio 0" >> ${LRL}
 
-echo $DBNAME 0 $CLUSTER > $CDB2_CONFIG
-echo "comdb2_config:default_type=testsuite" >> $CDB2_CONFIG
-echo "cluster nodes $CLUSTER" >> $DBDIR/$DBNAME.lrl
-
-for node in $CLUSTER; do #verify we can ssh to nodes
-    if [ $node == $myhostname ] ; then
-        continue
+    pmux_port=5105
+    pmux_cmd='pmux -n'
+    if [ -n "$PMUXPORT" ] ; then
+        pmux_port=$PMUXPORT
+        pmux_socket=/tmp/pmux.socket.$PMUXPORT
+        pmux_port_range="-r 21000:22000"
+        pmux_cmd="pmux -n -p $PMUXPORT -b $pmux_socket $pmux_port_range"
+        echo "comdb2_config:portmuxport=$PMUXPORT" >> $CDB2_CONFIG
+        echo "portmux_port $PMUXPORT" >> ${LRL}
+        echo "portmux_bind_path $pmux_socket" >> ${LRL}
     fi
-    hst=$(ssh -o StrictHostKeyChecking=no $node "hostname")
-    if [ "x$hst" == "x" ] ; then
-        failexit "cant get hostname on $node"
+
+    df $DBDIR | awk '{print $1 }' | grep "tmpfs\|nfs" > /dev/null && echo "setattr directio 0" >> ${LRL}
+
+    echo $DBNAME 0 $CLUSTER > $CDB2_CONFIG
+    echo "comdb2_config:default_type=testsuite" >> $CDB2_CONFIG
+    echo "cluster nodes $CLUSTER" >> $DBDIR/$DBNAME.lrl
+    set +e
+    $COMDB2_EXE --create --lrl ${LRL} --pidfile ${TMPDIR}/$DBNAME.pid $PARAMS &> $LOGDIR/${DBNAME}.init
+    rc=$?
+    rm -f ${DBNAME}.trap
+    if [[ $rc -ne 0 ]] ; then
+        echo "Error rc=$rc while initializing DB, see $LOGDIR/${DBNAME}.init "
+        exit 1
     fi
-done
 
-set +e
-
-pmux_port=5105
-pmux_cmd='pmux -n'
-if [ -n "$PMUXPORT" ] ; then
-    pmux_port=$PMUXPORT
-    pmux_socket=/tmp/pmux.socket.$PMUXPORT
-    pmux_port_range="-r 21000:22000"
-    pmux_cmd="pmux -n -p $PMUXPORT -b $pmux_socket $pmux_port_range"
-    echo "comdb2_config:portmuxport=$PMUXPORT" >> $CDB2_CONFIG
-    echo "portmux_port $PMUXPORT" >> ${LRL}
-    echo "portmux_bind_path $pmux_socket" >> ${LRL}
+    echo "${DBNAME} created successfully"
 fi
-
-
-for csc2 in $(ls *.csc2 2>/dev/null); do
-    table=${csc2%%.csc2}
-    cp $PWD/$csc2 $DBDIR/
-done >> $DBDIR/${DBNAME}.lrl
-
-
-$COMDB2_EXE --create --lrl $DBDIR/${DBNAME}.lrl --pidfile ${TMPDIR}/$DBNAME.pid $DBNAME  >$DBDIR/logs/${DBNAME}.init 2>&1
-rc=$?
-rm -f ${DBNAME}.trap
-if [[ $rc -ne 0 ]]; then
-    echo "Error rc=$rc while initializing DB, see $TESTDIR/logs/${DBNAME}.init "
-    exit 1
-fi
-echo "${DBNAME} created successfully"
 
 #set -e  # from here, a bad rc will mean failure and exit
 
 
 echo "$DBNAME: copying to cluster"
 for node in $CLUSTER; do
-    if [ $node == $myhostname ] ; then # skip copying to ourself
-        continue
+    if [ $node == $myhostname ] ; then
+        continue        # no copying to self
     fi
 
-    ssh -o StrictHostKeyChecking=no $node "mkdir -p $DBDIR/logs/ $DBDIR/var/log/cdb2 $DBDIR/tmp/cdb2" < /dev/null
-    ssh -o StrictHostKeyChecking=no $node "$pmux_cmd" &>> $DBDIR/setup.log < /dev/null
+    ssh -o StrictHostKeyChecking=no $node "mkdir -p $LOGDIR $DBDIR/var/log/cdb2 $DBDIR/tmp/cdb2" < /dev/null
+    ssh -o StrictHostKeyChecking=no $node "$pmux_cmd" &>> $LOGDIR/setup.log < /dev/null
 
     loccomdb2ar_exopts=`ssh -o StrictHostKeyChecking=no $node "which $COMDB2_EXE"`
-    COMDB2AR_EXOPTS="-x $loccomdb2ar_exopts" copycomdb2 $DBDIR/${DBNAME}.lrl ${node}: &> $DBDIR/logs/${DBNAME}.${node}.copy
+    COMDB2AR_EXOPTS="-x $loccomdb2ar_exopts" $COPYCOMDB2_EXE ${LRL} ${node}: &> ${LOGDIR}/${DBNAME}.${node}.copy
     if [[ $? -ne 0 ]]; then
-        echo "FAILED: copycomdb2 $DBDIR/${DBNAME}.lrl ${node}: "
-        echo "see $DBDIR/logs/${DBNAME}.${node}.copy "
+        echo "FAILED: $COPYCOMDB2_EXE ${LRL} ${node}: "
+        echo "see $LOGDIR/${DBNAME}.${node}.copy "
         exit 1
     fi
 done
@@ -169,30 +172,43 @@ CMD="source ${DBDIR}/replicant_vars ; $COMDB2_EXE ${DBNAME} -lrl $DBDIR/${DBNAME
 echo "$DBNAME: starting"
 for node in $CLUSTER; do
     if [ $node == $myhostname ] ; then # dont ssh to ourself -- just start db locally
-        $COMDB2_EXE ${DBNAME} -lrl $DBDIR/${DBNAME}.lrl -pidfile ${TMPDIR}/${DBNAME}.${node}.pid 2>&1 | gawk '{ print strftime("%H:%M:%S>"), $0; fflush(); }' >$DBDIR/logs/${DBNAME}.${node}.db 2>&1 &
+            if [[ -n ${DEBUG_PREFIX} && ${INTERACTIVE_DEBUG} -eq 1 ]]; then
+                echo -e "!$TESTCASE: Execute the following command on ${node}: ${TEXTCOLOR}${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} -pidfile ${TMPDIR}/${DBNAME}.${node}.pid${NOCOLOR}"
+            else
+                ${DEBUG_PREFIX} $COMDB2_EXE ${PARAMS} --lrl ${LRL} -pidfile ${TMPDIR}/${DBNAME}.${node}.pid &> $LOGDIR/${DBNAME}.${node}.db &
+            fi
         continue
     fi
 
-    scp -o StrictHostKeyChecking=no ${DBDIR}/replicant_vars $node:${DBDIR}/replicant_vars &>> $DBDIR/setup.log
+    if [[ -n ${DEBUG_PREFIX} && ${INTERACTIVE_DEBUG} -eq 1 ]]; then
+        echo -e "$DBNAME: Execute the following command on ${node}: ${TEXTCOLOR}${CMD}${NOCOLOR}"
+        continue
+    fi
+    scp -o StrictHostKeyChecking=no ${DBDIR}/replicant_vars $node:${DBDIR}/replicant_vars &>> $LOGDIR/setup.log
     # redirect output from CMD to a subshell which runs awk to prepend time
-    ssh -o StrictHostKeyChecking=no -tt $node ${CMD} 2>&1 </dev/null > >(gawk '{ print strftime("%H:%M:%S>"), $0; fflush(); }' > $DBDIR/logs/${DBNAME}.${node}.db)  &
+    ssh -n -o StrictHostKeyChecking=no -tt $node ${CMD} &>$LOGDIR/${DBNAME}.${node}.db &
     # $! will be pid of ssh (if we had used pipe, $! would be pid of awk)
     echo $! > ${TMPDIR}/${DBNAME}.${node}.pid
 done
+
+if [[ -n ${DEBUG_PREFIX} && ${INTERACTIVE_DEBUG} -eq 1 ]]; then
+    exit 0
+fi
 
 set +e
 echo "$DBNAME: waiting until ready"
 sleep 1
 for node in $CLUSTER; do
-    out=$(cdb2sql ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
+    out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
     while  [[ "$out" != "1" ]]; do
         sleep 2
-        out=$(cdb2sql ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
+        out=$($CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' 2>&1)
+        $CDB2SQL_EXE ${CDB2_OPTIONS} --tabs --host $node $DBNAME 'select 1' &> $LOGDIR/${DBNAME}.${node}.conn
     done
 done
 
-n=$(cdb2sql ${CDB2_OPTIONS} -tabs $DBNAME --host $node 'exec procedure sys.cmd.send("bdb cluster")' | grep "lsn" | wc -l)
+n=$($CDB2SQL_EXE ${CDB2_OPTIONS} -tabs $DBNAME --host $node 'exec procedure sys.cmd.send("bdb cluster")' | grep "lsn" | wc -l)
 echo "$DBNAME: Cluster is running with $n nodes. You can query it with:"
-echo "   cdb2sql ${CDB2_OPTIONS} $DBNAME default 'select 1'"
+echo "   $CDB2SQL_EXE ${CDB2_OPTIONS} $DBNAME default 'select 1'"
 
 exit 0
