fixes for renametable test

diff --git a/tests/renametable.test/runit b/tests/renametable.test/runit
--- a/tests/renametable.test/runit
+++ b/tests/renametable.test/runit
@@ -51,8 +51,15 @@ EOF
 
 df=`diff output.txt reqoutput.txt`
 if [ $? -ne 0 ] ; then
-    echo "Failed"
-    exit 1
+     echo "  ^^^^^^^^^^^^"
+     echo "The above testcase (${testcase}) has failed!!!"
+     echo " "
+     echo "Use 'diff <expected-output> <my-output>' to see why:"
+     echo "> diff ${PWD}/output.txt ${PWD}/reqoutput.txt"
+     echo " "
+     diff output.txt reqoutput.txt
+     echo " "
+     exit 1
 fi 
 
 echo "Success"
