Fail selectv that requires too many cursors; do not try to read or write beyond the recording array.
re: 179191425

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

diff --git a/tests/selectv_timepart.test/runit b/tests/selectv_timepart.test/runit
--- a/tests/selectv_timepart.test/runit
+++ b/tests/selectv_timepart.test/runit
@@ -89,11 +89,21 @@ cdb2sql ${CDB2_OPTIONS} $dbname default - < writer.sql >> $OUT 2>&1
 
 sleep 20
 
-difs=`diff $OUT $OUT.expected`
-if [[ $? != 0 ]]; then
-   echo "FAILURE"
-   exit 1
+
+echo cdb2sql ${CDB2_OPTIONS} $dbname default "create table test(a int unique, b int) partitioned by time period 'daily' retention 20 start '20250101T'"
+cdb2sql ${CDB2_OPTIONS} $dbname default "create table test(a int unique, b int) partitioned by time period 'daily' retention 20 start '20250101T'"
+if (( $? != 0 )) ; then
+    echo "FAILURE create partitioned table"
+    exit 1
 fi
+
+cdb2sql -f q.txt ${CDB2_OPTIONS} $dbname default -  >> $OUT 2>&1
+if (( $? == 0 )) ; then
+    echo "FAILURE to block too many cursors selectv"
+    exit 1
+fi
+
+difs=`diff $OUT $OUT.expected`
 if [[ ! -z "${difs}" ]] ; then
    echo "diff $OUT $OUT.expected"
    echo ${difs}
