PR switches remtran implementation to run over cdb2api instead of legacy remtran plugin. Currently it supports non-2pc transactions and socksql transaction isolation. It provides protocol versioning and solves the stale schema change issue, which the previous implementation did not support.
PR adds a fdb compatibility testcase to check for ability to execute cross-cluster queries and writes with older and newer protocol
versions.

The new implementation eliminates some of the fragile synchronization between read and write remote cursors in the previous implementation,
by running the write statements remotely (push mode extended to writes).

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

diff --git a/tests/fdb_compat.test/runit b/tests/fdb_compat.test/runit
--- a/tests/fdb_compat.test/runit
+++ b/tests/fdb_compat.test/runit
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
+bash -n "$0" | exit 1
 
 # Remote cursor moves testcase for comdb2
 ################################################################################
+
 
 # args
 # <dbname> <dbdir> <testdir> <autodbname> <autodbnum> <cluster>
@@ -16,21 +18,18 @@ for required in $vars; do
     fi
 done
 
-opt=
-if [[ ! -z $2 ]]; then
-    opt=$2
-fi
 
 #run tests
 echo "Starting tests"
-echo ./writes_remsql_names.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBDIR $TESTDIR $opt
-./writes_remsql_names.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBDIR $TESTDIR $opt
+echo ./test_fdb.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBDIR $TESTDIR
+./test_fdb.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBDIR $TESTDIR
 result=$?
 
+
 if (( $result != 0 )) ; then
-   echo "FAILURE"
+   echo "Failure"
    exit 1
 fi
 
 
-echo "SUCCESS"
+echo "Success"
