add more checks of figerprints to test

diff --git a/tests/eventlog.test/runit b/tests/eventlog.test/runit
--- a/tests/eventlog.test/runit
+++ b/tests/eventlog.test/runit
@@ -39,24 +39,32 @@ df $DBDIR | awk '{print $1 }' | grep "tmpfs\|nfs" && echo "setattr directio 0" >
 ${COMDB2_EXE} ${DBNAME} --create --dir $DBDIR --lrl $DBDIR/${DBNAME}.lrl &> out
 grep "Created database" out || failexit "expected 'Created database'"
 
-echo "name    $DB" >> $DBDIR/${DBNAME}.lrl
+echo "name    $DBNAME" >> $DBDIR/${DBNAME}.lrl
 echo "dir     $DBDIR" >> $DBDIR/${DBNAME}.lrl
 mkdir -p $TESTDIR/var/log/cdb2
 mkdir -p $TMPDIR
 
 
 echo "comdb2_config:default_type=local" >> $CDB2_CONFIG
-${COMDB2_EXE} $DBNAME --no-global-lrl --lrl $DBDIR/${DBNAME}.lrl --pidfile ${TMPDIR}/${DBNAME}.pid &> $TESTDIR/logs/${DBNAME}.db &
+$DEBUGGER ${COMDB2_EXE} $DBNAME --no-global-lrl --lrl $DBDIR/${DBNAME}.lrl --pidfile ${TMPDIR}/${DBNAME}.pid &> $TESTDIR/logs/${DBNAME}.db &
 
 waitfordb $DBNAME
-
-res=`cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "select comdb2_host()"`
-assertres $res $HOSTNAME
+#TODO: this call causes for the first 'select 1' to have the wrong fingerprint even for master branch: cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "select comdb2_hostname()"
 
 cdb2sql ${CDB2_OPTIONS} $DBNAME default "exec procedure sys.cmd.send('reql events detailed on')"
 
 res=`cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "select 1"`
 assertres $res 1
+
+res=`cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "select 2"`
+assertres $res 2
+
+res=`cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "select 2"`
+assertres $res 2
+
+res=`cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "select 1"`
+assertres $res 1
+
 
 res=`cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "nonsense" 2>&1`
 exp="[nonsense] failed with rc -3 near \"nonsense\": syntax error"
@@ -78,33 +86,61 @@ fi
 wc $logfl
 zcat $logfl > $logflunziped
 
-grep '"sql","sql": "select 1"' $logflunziped | python -c "import sys, json; txt=json.load(sys.stdin); print txt['fingerprint']" > out.txt
+echo check all .*sql entries for fingerprint
+echo 'f0b766640ca06b156a8bce8b546931c8' > exp.txt
+IFS=$'\n'
+for line in `grep 'sql","sql": "select 1"' $logflunziped ` ; do 
+    echo $line | python -c "import sys, json; txt=json.load(sys.stdin); print txt['fingerprint']" > out.txt
+    if ! diff out.txt exp.txt ; then
+        failexit 'output is different from expected'
+    fi 
+done
 
-echo 'f755c0df1b9c32e99f201e77b29d128f' > exp.txt
+echo check all .*sql entries for fingerprint
+echo 'f0b766640ca06b156a8bce8b546931c8' > exp.txt
+IFS=$'\n'
+for line in `grep 'sql","sql": "select 2"' $logflunziped ` ; do 
+    echo $line | python -c "import sys, json; txt=json.load(sys.stdin); print txt['fingerprint']" > out.txt
+    if ! diff out.txt exp.txt ; then
+        failexit 'output is different from expected'
+    fi 
+done
 
-if ! diff out.txt exp.txt ; then
-    failexit 'output is different from expected'
-fi
+echo check all .*sql entries for fingerprint
+echo '00000000000000000000000000000000' > exp.txt
+grep 'sql","sql": "nonsense"' $logflunziped | while read line ;
+do
+    echo $line | python -c "import sys, json; txt=json.load(sys.stdin); print txt['error_code']; print txt['error']; print txt['fingerprint']" > out.txt
+    if ! diff out.txt exp.txt ; then
+        failexit 'output is different from expected'
+    fi
+done
 
-
-grep '"sql","sql": "nonsense"' $logflunziped | python -c "import sys, json; txt=json.load(sys.stdin); print txt['error_code']; print txt['error']; print txt['fingerprint']" > out.txt
-
+echo check the sql parameter now
 echo '1
 near "nonsense": syntax error
 00000000000000000000000000000000' > exp.txt
-
+grep '"sql","sql": "nonsense"' $logflunziped | python -c "import sys, json; txt=json.load(sys.stdin); print txt['error_code']; print txt['error']; print txt['fingerprint']" > out.txt
 if ! diff out.txt exp.txt ; then
     failexit 'output is different from expected'
 fi
 
-
-grep '"sql","sql": "select \* from nonexistent"' $logflunziped | python -c "import sys, json; txt=json.load(sys.stdin); print txt['error_code']; print txt['error']; print txt['fingerprint']" > out.txt
+echo check all .*sql entries for fingerprint
+echo 'e95d2065e6ee80006932de9fe9dbbb42' > exp.txt
+grep 'sql","sql": "select \* from nonexistent"' $logflunziped | while read line ; 
+do
+    echo $line | python -c "import sys, json; txt=json.load(sys.stdin); print txt['error_code']; print txt['error']; print txt['fingerprint']" > out.txt
 #grep '"sql","sql": "select \* from nonexistent"' $logflunziped | sed -e 's/[{}]/''/g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | grep "fingerprint\|error" > out.txt
+    if ! diff out.txt exp.txt ; then
+        failexit 'output is different from expected'
+    fi
+done
 
+echo check the sql parameter now
 echo '1
 no such table: nonexistent
 e95d2065e6ee80006932de9fe9dbbb42' > exp.txt
-
+grep '"sql","sql": "select \* from nonexistent"' $logflunziped | python -c "import sys, json; txt=json.load(sys.stdin); print txt['error_code']; print txt['error']; print txt['fingerprint']" > out.txt
 if ! diff out.txt exp.txt ; then
     failexit 'output is different from expected'
 fi
