Enable CREATE UNIQUE INDEX to handle duplicate NULL values when opted-in via 'uniqnulls' index flag (#864)
These changes allow the 'uniqnulls' flag to be specified in the CSC2 schema for an index and when CREATE UNIQUE INDEX is used on a column that permits NULL values.

diff --git a/tests/constraints.test/runit b/tests/constraints.test/runit
--- a/tests/constraints.test/runit
+++ b/tests/constraints.test/runit
@@ -188,4 +188,63 @@ for testcase in $files ; do
 
 done
 
+### Tests for CREATE UNIQUE INDEX with multiple NULL values
+
+function failexit
+{
+    echo "Failed $1"
+    exit -1
+}
+
+function assertbadexitcode
+{
+    rc=$1
+    if [ $rc -eq 0 ] ; then
+        failexit "exit code is now $rc but should not be 0"
+    fi
+}
+
+function assertres
+{
+    if [ $# != 2 ] ; then
+        failexit "res is $res, target is $target, one or more is blank"
+    fi
+    res=$1
+    target=$2
+    if [ "$res" != "$target" ] ; then
+        failexit "res is $res but should be $target"
+    fi
+}
+
+set -- +o errexit
+echo "create and use 'uniqnulls' enabled tables with foreign keys"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "create table j5(x INTEGER)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "create unique index j5_x on j5(x)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j5 values(NULL)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j5 values(NULL)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j5 values(1)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j5 values(2)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j5 values(3)"
+res=`cdb2sql --tabs ${CDB2_OPTIONS} $a_dbn default "select x from j5 order by x"`
+assertres "${res}" $'NULL\nNULL\n1\n2\n3'
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "exec procedure sys.cmd.verify('j5')"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "create table j6(y INTEGER, x INTEGER, FOREIGN KEY(x) REFERENCES j5(x))"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "create unique index j6_y on j6(y)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j6 values(-1, NULL)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j6 values(0, NULL)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j6 values(1, 1)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j6 values(2, 2)"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "insert into j6 values(3, 3)"
+res=`cdb2sql --tabs ${CDB2_OPTIONS} $a_dbn default "select y from j6 order by y"`
+assertres "${res}" $'-1\n0\n1\n2\n3'
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "exec procedure sys.cmd.verify('j6')"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "delete from j5 where x is null"
+res=`cdb2sql --tabs ${CDB2_OPTIONS} $a_dbn default "select x from j5 order by x"`
+assertres "${res}" $'1\n2\n3'
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "exec procedure sys.cmd.verify('j5')"
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "delete from j6 where x is null"
+res=`cdb2sql --tabs ${CDB2_OPTIONS} $a_dbn default "select y from j6 order by y"`
+assertres "${res}" $'1\n2\n3'
+cdb2sql ${CDB2_OPTIONS} $a_dbn default "exec procedure sys.cmd.verify('j6')"
+
 echo "Testcase passed."
