feat: update Hibernate version from 5.x to 6.x
Signed-off-by: Mikhail Laptev <mlaptev@bloomberg.net>

diff --git a/tests/timepart_trunc.test/runit b/tests/timepart_trunc.test/runit
--- a/tests/timepart_trunc.test/runit
+++ b/tests/timepart_trunc.test/runit
@@ -524,7 +524,6 @@ $cmd "select * from comdb2_tables where tablename='t17'" >> $OUT 2>&1
 echo $cmd "select * from comdb2_timepartshards where name='t17'"
 $cmd "select * from comdb2_timepartshards where name='t17'" >> $OUT 2>&1
 
-
 echo $cmd "create table teststatsize(a int)"
 $cmd "create table teststatsize(a int)" >> $OUT 2>&1
 
@@ -548,6 +547,97 @@ if (( $? != 0 )) ; then
     echo "FAILURE to rebuild partition t18"
     exit 1
 fi
+
+header 18 "Test block alter"
+echo $cmd "create table t19(a int)"
+$cmd "create table t19(a int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create table t19"
+   exit 1
+fi
+
+echo $cmd "put tunable disable_tagged_api_writes 0"
+if [[ -n "$CLUSTER" ]]; then
+    for node in $CLUSTER; do
+        cdb2sql --host $node $dbname --host $node "put tunable disable_tagged_api_writes 0"
+        if (( $? != 0 )) ; then
+            echo "FAILURE node ${node} to put tunable to 0"
+            exit 1
+        fi
+    done
+else
+    $cmd "put tunable disable_tagged_api_writes 0"
+    if (( $? != 0 )) ; then
+        echo "FAILURE to put tunable to 0"
+        exit 1
+    fi
+fi
+
+echo $cmd "ALTER TABLE t19 PARTITIONED BY TIME PERIOD 'daily' RETENTION 3 start '2024-01-01T'"
+$cmd "ALTER TABLE t19 PARTITIONED BY TIME PERIOD 'daily' RETENTION 3 start '2024-01-01T'"
+if (( $? == 0 )) ; then
+   echo "FAILURE to block alter partition when tag writes are enabled"
+   exit 1
+fi
+
+echo $cmd "put tunable disable_tagged_api_writes 1"
+if [[ -n "$CLUSTER" ]]; then
+    for node in $CLUSTER; do
+        cdb2sql --host $node $dbname --host $node "put tunable disable_tagged_api_writes 1"
+        if (( $? != 0 )) ; then
+            echo "FAILURE node ${node} to put tunable to 1"
+            exit 1
+        fi
+    done
+else
+    $cmd "put tunable disable_tagged_api_writes 1"
+    if (( $? != 0 )) ; then
+        echo "FAILURE to put tunable to 1"
+        exit 1
+    fi
+fi
+
+header 19 "Test check for partition new over old shards"
+echo $cmd "create table t20(a int)"
+$cmd "create table t20(a int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create t20"
+   exit 1
+fi
+
+starttime=`perl -MPOSIX -le 'local $ENV{TZ}=":/usr/share/zoneinfo/UTC"; print strftime "%Y-%m-%dT%H%M%S UTC", localtime(time()-3*24*3600-60)'`
+echo $cmd "CREATE TIME PARTITION ON t20 as tv20 PERIOD 'daily' RETENTION 2 START '${starttime}'"
+$cmd "CREATE TIME PARTITION ON t20 as tv20 PERIOD 'daily' RETENTION 2 START '${starttime}'"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create time partition tv20"
+   exit 1
+fi
+
+sleep 30
+
+echo $cmd "drop time partition tv20"
+$cmd "drop time partition tv20"
+if (( $? != 0 )) ; then
+   echo "FAILURE to drop time partition tv20"
+   exit 1
+fi
+
+sleep 10
+
+echo $cmd "create table t20(a int)"
+$cmd "create table t20(a int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to recreate t20"
+   exit 1
+fi
+
+echo $cmd "alter table t20 partitioned by time period 'daily' retention 2 start '20240901T'"
+$cmd "alter table t20 partitioned by time period 'daily' retention 2 start '20240901T'"
+if (( $? == 0 )) ; then
+   echo "FAILURE to block creating overlapping shards"
+   exit 1
+fi
+
 
 # we need to scrub dbname from alpha
 sed "s/dorintdb/$dbname/g; s#\${CDB2_OPTIONS}#${CDB2_OPTIONS}#g" $OUT.alpha > $OUT.alpha.actual
