tunable to disable tag writes
disable alter partition if tag reads or writes are not disabled

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

diff --git a/tests/timepart_trunc.test/runit b/tests/timepart_trunc.test/runit
--- a/tests/timepart_trunc.test/runit
+++ b/tests/timepart_trunc.test/runit
@@ -524,7 +524,6 @@ $cmd "select * from comdb2_tables where tablename='t17'" >> $OUT 2>&1
 echo $cmd "select * from comdb2_timepartshards where name='t17'"
 $cmd "select * from comdb2_timepartshards where name='t17'" >> $OUT 2>&1
 
-
 echo $cmd "create table teststatsize(a int)"
 $cmd "create table teststatsize(a int)" >> $OUT 2>&1
 
@@ -547,6 +546,35 @@ $cmd "rebuild t18"
 if (( $? != 0 )) ; then
     echo "FAILURE to rebuild partition t18"
     exit 1
+fi
+
+header 18 "Test block alter"
+echo $cmd "create table t19(a int)"
+$cmd "create table t19(a int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create table t19"
+   exit 1
+fi
+
+echo $cmd "put tunable disable_tagged_api_writes 0"
+$cmd "put tunable disable_tagged_api_writes 0"
+if (( $? != 0 )) ; then
+   echo "FAILURE to put tunable to 0"
+   exit 1
+fi
+
+echo $cmd "ALTER TABLE t19 PARTITIONED BY TIME PERIOD 'daily' RETENTION 3 start '2024-01-01T'"
+$cmd "ALTER TABLE t19 PARTITIONED BY TIME PERIOD 'daily' RETENTION 3 start '2024-01-01T'"
+if (( $? == 0 )) ; then
+   echo "FAILURE to block alter partition when tag writes are enabled"
+   exit 1
+fi
+
+echo $cmd "put tunable disable_tagged_api_writes 1"
+$cmd "put tunable disable_tagged_api_writes 1"
+if (( $? != 0 )) ; then
+   echo "FAILURE to put tunable to 1"
+   exit 1
 fi
 
 # we need to scrub dbname from alpha
