block creating a partition with shards matching existing shards
Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

diff --git a/tests/timepart_trunc.test/runit b/tests/timepart_trunc.test/runit
--- a/tests/timepart_trunc.test/runit
+++ b/tests/timepart_trunc.test/runit
@@ -565,9 +565,51 @@ if (( $? != 0 )) ; then
    exit 1
 fi
 
-header 18 "Test block put retention"
+header 18 "Test check for partition new over old shards"
+echo $cmd "create table t19(a int)"
+$cmd "create table t19(a int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create t19"
+   exit 1
+fi
+
+starttime=`perl -MPOSIX -le 'local $ENV{TZ}=":/usr/share/zoneinfo/UTC"; print strftime "%Y-%m-%dT%H%M%S UTC", localtime(time()-3*24*3600-60)'`
+echo $cmd "CREATE TIME PARTITION ON t19 as tv19 PERIOD 'daily' RETENTION 2 START '${starttime}'"
+$cmd "CREATE TIME PARTITION ON t19 as tv19 PERIOD 'daily' RETENTION 2 START '${starttime}'"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create time partition tv19"
+   exit 1
+fi
+
+sleep 30
+
+echo $cmd "drop time partition tv19"
+$cmd "drop time partition tv19"
+if (( $? != 0 )) ; then
+   echo "FAILURE to drop time partition tv19"
+   exit 1
+fi
+
+sleep 10
+
+echo $cmd "create table t19(a int)"
+$cmd "create table t19(a int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to recreate t19"
+   exit 1
+fi
+
+echo $cmd "alter table t19 partitioned by time period 'daily' retention 2 start '20240901T'"
+$cmd "alter table t19 partitioned by time period 'daily' retention 2 start '20240901T'"
+if (( $? == 0 )) ; then
+   echo "FAILURE to block creating overlapping shards"
+   exit 1
+fi
+
+header 19 "Test block put retention"
 echo $cmd "put time partition t17 retention 20"
 $cmd "put time partition t17 retention 20" >> $OUT 2>&1
+
 
 # we need to scrub dbname from alpha
 sed "s/dorintdb/$dbname/g; s#\${CDB2_OPTIONS}#${CDB2_OPTIONS}#g" $OUT.alpha > $OUT.alpha.actual
