interm
working simple test

testcase

format

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

diff --git a/tests/timepart_trunc.test/runit b/tests/timepart_trunc.test/runit
--- a/tests/timepart_trunc.test/runit
+++ b/tests/timepart_trunc.test/runit
@@ -417,6 +417,47 @@ $cmd "select * from t14 order by 1" >> $OUT
 
 timepart_stats 0
 
+header 15 "Test ALTER table MERGE"
+echo $cmd "CREATE TABLE t15(a int, b int)"
+$cmd "CREATE TABLE t15(a int, b int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create table t15"
+   exit 1
+fi
+echo $cmd "CREATE TABLE t16(a int)"
+$cmd "CREATE TABLE t16(a int)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to create table t16"
+   exit 1
+fi
+
+echo $cmd "insert into t15 values (11,12), (22,23), (33,34)"
+$cmd "insert into t15 values (11,12), (22,23), (33,34)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to insert into t15"
+   exit 1
+fi
+
+echo $cmd "insert into t16 values (100), (200)"
+$cmd "insert into t16 values (100), (200)"
+if (( $? != 0 )) ; then
+   echo "FAILURE to insert into t16"
+   exit 1
+fi
+
+echo $cmd "alter table t15 drop column b, merge t16"
+$cmd "alter table t15 drop column b, merge t16"
+if (( $? != 0 )) ; then
+   echo "FAILURE to alter merge"
+   exit 1
+fi
+
+echo $cmd "select * from t15 order by a"
+$cmd "select * from t15 order by a" >> $OUT
+
+echo $cmd "select * from t16 order by a"
+$cmd "select * from t16 order by a" >> $OUT 2>&1
+
 # we need to scrub dbname from alpha
 sed "s/dorintdb/$dbname/g; s#\${CDB2_OPTIONS}#${CDB2_OPTIONS}#g" $OUT.alpha > $OUT.alpha.actual
 
