block put retetion for truncate partitions
Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

diff --git a/tests/timepart_trunc.test/runit b/tests/timepart_trunc.test/runit
--- a/tests/timepart_trunc.test/runit
+++ b/tests/timepart_trunc.test/runit
@@ -665,6 +665,12 @@ if (( $? != 0 )) ; then
    exit 1
 fi
 
+header 22 "Test put retention block for truncate partitions"
+$cmdt "put time partition t retention 1"
+if (( $? == 0 )) ; then
+   echo "FAILURE to block put retention"
+   exit 1
+fi
 
 # we need to scrub dbname from alpha
 sed "s/dorintdb/$dbname/g; s#\${CDB2_OPTIONS}#${CDB2_OPTIONS}#g" $OUT.alpha > $OUT.alpha.actual
