erroneously retreived copy from master branch for insert_lots.test

diff --git a/tests/insert_lots.test/runit b/tests/insert_lots.test/runit
--- a/tests/insert_lots.test/runit
+++ b/tests/insert_lots.test/runit
@@ -3,7 +3,6 @@ bash -n "$0" | exit 1
 
 set -e
 set -x
-source ${TESTSROOTDIR}/tools/runit_common.sh
 
 # Debug variable
 debug=0
@@ -23,6 +22,20 @@ failexit()
 {
     echo "Failed $1"
     exit -1
+}
+
+assertcnt ()
+{
+    target=$1
+    cnt=$(cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select count(*) from t1")
+    if [ $? -ne 0 ] ; then
+        echo "assertcnt: select error"
+    fi
+
+    #echo "count is now $cnt"
+    if [[ $cnt != $target ]] ; then
+        failexit "count is now $cnt but should be $target"
+    fi
 }
 
 assert_vers()
@@ -50,13 +63,39 @@ assert_schema()
     fi
 }
 
+do_verify()
+{
+    cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure sys.cmd.verify('t1')" &> verify.out
+
+    if ! grep succeeded verify.out > /dev/null ; then
+        failexit "Verify"
+    fi
+}
+
+assertres ()
+{
+    if [ $# != 2 ] ; then 
+        failexit "number of parameters passed is $# but expecting 2"
+    fi
+    res=$1
+    target=$2
+    if [ "$res" != "$target" ] ; then
+        failexit "res is $res but should be $target"
+    fi
+}
+
+#test inserting a large number of items via generate series and query for them
 gen_series_test()
 {
     MAX=9000
     cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "create table t2 (i int)"
     cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "insert into t2 select * from generate_series(1, $MAX) "
     cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select distinct i from t2" | sort -n > gen.out
-    seq 1 $MAX > gen.exp
+    i=1
+    while [ $i -le $MAX ] ; do 
+        echo $i >> gen.exp
+        let i=i+1
+    done
     if ! diff gen.out gen.exp ; then 
         failexit 'genseries content not what it is expected'
     fi
@@ -71,12 +110,12 @@ TRANSIZE=0
 gen_series_test
 
 time ${TESTSBUILDDIR}/insert_lots_mt $dbnm $THRDS $CNT $ITERATIONS $TRANSIZE> ins1.out
-assertcnt t1 $((THRDS * CNT * ITERATIONS))
+assertcnt $((THRDS * CNT * ITERATIONS))
 
 cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "truncate t1"
 
 TRANSIZE=2800
 time ${TESTSBUILDDIR}/insert_lots_mt $dbnm $THRDS $CNT $ITERATIONS $TRANSIZE> ins2.out
-assertcnt t1 $((THRDS * CNT * ITERATIONS))
+assertcnt $((THRDS * CNT * ITERATIONS))
 
 echo "Success"
