Changed copycomdb2 to allow easy replicant copying.

diff --git a/db/copycomdb2 b/db/copycomdb2
--- a/db/copycomdb2
+++ b/db/copycomdb2
@@ -80,9 +80,12 @@ Other options:
     -b          Serialize a backup of a database to stdout
     -r          Restore a backup of a database from stdin
     -p          Copy only the incremental differences
-    -H          Creates a physical replicant. Automatically calls -C strip flag.
-    -y          Specify which machines a physical replicant will copy from.
-                This flag must be specified if the copied db does not have a cluster.
+    -H <db name>  Creates a physical replicant. Automatically calls -C strip flag.
+    -y '<remote>' Specify which machines a physical replicant will copy from.
+                  This flag must be specified if the copied db does not have a cluster.
+                  Delimit each machine name with whitespace
+                  Note: comdb2ar will fail if no cluster line was specified from 
+                  the lrl file and -a was not specified
 \n"
 
    exit 1
@@ -132,8 +135,10 @@ max_du_percent=95
 partial=no
 partialopts=
 outmode=x
-phys_rep=no
+phys_repmode=no
+phys_name=
 phys_copy_from=
+phys_copy_flag=no
 
 [ -z "$comdb2ar" ] && comdb2ar="${PREFIX}/bin/comdb2ar"
 [ -z "$lz4" ] && lz4="${PREFIX}/bin/lz4"
@@ -157,7 +162,7 @@ if [[ ! -x $lz4 ]]; then
    fi
 fi
 
-set - `getopt "LC:ht:l:rdsSx:fmaZu:bpHy:" "$@"` || die
+set - `getopt "LC:ht:l:rdsSx:fmaZu:bpH:y:" "$@"` || die
 for arg in "$@" ; do
     case "$arg" in
         -h)
@@ -231,11 +236,13 @@ for arg in "$@" ; do
             shift
             ;;
 
-        -H) phys_rep=yes
-            shift
+        -H) phys_repmode=yes
+            phys_name="$2"
+            shift 2
             ;;
 
         -y) phys_copy_from="$2"
+            phys_copy_flag=yes
             shift 2
             ;;
 
@@ -248,6 +255,10 @@ done
 
 [ $copy_data = no -a $copy_lrls = no ] && die "cannot use -s and -d together"
 
+# restrict physical replicant mode
+[ $movemode = yes -a $phys_repmode = yes ] && die "cannot replicate and local move"
+[ $backupmode = yes -a $phys_repmode = yes ] && die "cannot replicate and backup"
+[ $restoremode = yes -a $phys_repmode = yes ] && die "cannot replicate and restore"
 
 # Get source file and host
 if [[ $restoremode = no ]]; then
@@ -429,6 +440,8 @@ exopts="-C $cluster_info -u $max_du_percent "
 
 [ $copy_data = no ]             && aropts="$aropts -s"
 [ $disable_log_delete = no ]    && aropts="$aropts -L"
+[ $phys_repmode = yes ]         && aropts="$aropts -E $phys_name" && exopts="$exopts -R"
+[ $phys_copy_flag = yes ]       && aropts="$aropts -a $phys_copy_from"
 
 if [ $restoremode = yes ]; then
     $IONICE $lz4 -d stdin stdout | $comdb2ar $COMDB2AR_AROPTS $exopts x $destlrldir $destdbdir 2>$arstatus 
