More work in progress.

diff --git a/tests/tmptbl_leak.test/runit b/tests/tmptbl_leak.test/runit
--- a/tests/tmptbl_leak.test/runit
+++ b/tests/tmptbl_leak.test/runit
@@ -22,30 +22,63 @@ for i in `seq 1 $N` ; do
   cdb2sql -s ${CDB2_OPTIONS} $dbnm default "SELECT t1.x, t1.y FROM t1 UNION SELECT t2.x, t2.y FROM t2 LEFT OUTER JOIN t1 t1a ON t2.x = t1a.x ORDER BY t1.x, t1.y" &> q_$i.out &
 done
 
+cdb2sql -s ${CDB2_OPTIONS} $dbnm default "EXEC PROCEDURE sys.cmd.send('temptable_counts')" &> temptable1.out
+cdb2sql -s ${CDB2_OPTIONS} $dbnm default "EXEC PROCEDURE sys.cmd.send('bdb temptable')" &> temptable2.out
+
 for i in `seq 1 $N` ; do
-  diff q_$i.out output.expect
-  if [[ $? -ne 0 ]]; then
-    echo "SELECT mismatch at $i"
+  testcase_output=$(cat q_$i.out)
+  expected_output=$(cat output.expect)
+  testcase_output_alt=$(cat output.expect.alt)
+
+  if [[ "$testcase_output" != "$expected_output" && "$testcase_output" != "$testcase_output_alt" ]]; then
+    diff q_$i.out output.expect
     diff q_$i.out output.expect.alt
-    if [[ $? -ne 0 ]]; then
-      echo "SELECT alt mismatch at $i"
-      echo "Failed."
-      exit 1
-    fi
+    echo "Failed."
+    exit 1
   fi
 done
 
-cdb2sql -s ${CDB2_OPTIONS} $dbnm default "EXEC PROCEDURE sys.cmd.send('bdb temptable')" &> temptable.out
+tempdata1=$(cat temptable1.out)
+regex1="Overall temptable count is ([0-9]+), SQL temptable count is ([0-9]+)"
 
-tempdata=`cat temptable.out`
-regex1="# returns            : ([0-9]+)"
-regex2="# borrows            : ([0-9]+)"
-
-if [[ $tempdata =~ $regex1 ]]; then
+if [[ $tempdata1 =~ $regex1 ]]; then
   num1="${BASH_REMATCH[1]}"
 
   if [[ -n $num1 ]]; then
-    if [[ $tempdata =~ $regex2 ]]; then
+    num2="${BASH_REMATCH[2]}"
+
+    if [[ -n $num2 ]]; then
+      if [[ $num1 -ne 0 ]]; then
+        echo "overall temptable count is not zero"
+        echo "Failed."
+        exit 1
+      fi
+      if [[ $num2 -ne 0 ]]; then
+        echo "SQL temptable count is not zero"
+        echo "Failed."
+        exit 1
+      fi
+    else
+      echo "missing SQL temptable count"
+      echo "Failed."
+      exit 1
+    fi
+  else
+    echo "missing overall temptable count"
+    echo "Failed."
+    exit 1
+  fi
+fi
+
+tempdata2=$(cat temptable2.out)
+regex2="# returns            : ([0-9]+)"
+regex3="# borrows            : ([0-9]+)"
+
+if [[ $tempdata2 =~ $regex2 ]]; then
+  num1="${BASH_REMATCH[1]}"
+
+  if [[ -n $num1 ]]; then
+    if [[ $tempdata2 =~ $regex3 ]]; then
       num2="${BASH_REMATCH[1]}"
 
       if [[ -n $num2 ]]; then
