Fix tests when running on a cluster.

diff --git a/tests/tmptbl_leak.test/runit b/tests/tmptbl_leak.test/runit
--- a/tests/tmptbl_leak.test/runit
+++ b/tests/tmptbl_leak.test/runit
@@ -82,75 +82,78 @@ wait
 sleep 60
 
 # cdb2sql -s ${CDB2_OPTIONS} $dbnm default "SELECT x, y FROM t1 ORDER BY x" &> t1_final.out
-cdb2sql -s ${CDB2_OPTIONS} $dbnm default "EXEC PROCEDURE sys.cmd.send('temptable_clear')" &> temptable0.out
-cdb2sql -s ${CDB2_OPTIONS} $dbnm default "EXEC PROCEDURE sys.cmd.send('temptable_counts')" &> temptable1.out
-cdb2sql -s ${CDB2_OPTIONS} $dbnm default "EXEC PROCEDURE sys.cmd.send('bdb temptable')" &> temptable2.out
 
-tempdata1=$(cat temptable1.out)
-regex1="Overall temptable count is ([0-9]+), SQL temptable count is ([0-9]+)"
+for node in ${CLUSTER} ; do
+  cdb2sql -s ${CDB2_OPTIONS} --host $node $dbnm default "EXEC PROCEDURE sys.cmd.send('temptable_clear')" &> temptable0_${node}.out
+  cdb2sql -s ${CDB2_OPTIONS} --host $node $dbnm default "EXEC PROCEDURE sys.cmd.send('temptable_counts')" &> temptable1_${node}.out
+  cdb2sql -s ${CDB2_OPTIONS} --host $node $dbnm default "EXEC PROCEDURE sys.cmd.send('bdb temptable')" &> temptable2_${node}.out
 
-if [[ $tempdata1 =~ $regex1 ]]; then
-  num1="${BASH_REMATCH[1]}"
+  tempdata1=$(cat temptable1_${node}.out)
+  regex1="Overall temptable count is ([0-9]+), SQL temptable count is ([0-9]+)"
 
-  if [[ -n $num1 ]]; then
-    num2="${BASH_REMATCH[2]}"
-
-    if [[ -n $num2 ]]; then
-      if [[ $num1 -ne 0 ]]; then
-        echo "overall temptable count is not zero"
-        echo "Failed."
-        exit 1
-      fi
-      if [[ $num2 -ne 0 ]]; then
-        echo "SQL temptable count is not zero"
-        echo "Failed."
-        exit 1
-      fi
-    else
-      echo "missing SQL temptable count"
-      echo "Failed."
-      exit 1
-    fi
-  else
-    echo "missing overall temptable count"
-    echo "Failed."
-    exit 1
-  fi
-fi
-
-tempdata2=$(cat temptable2.out)
-regex2="Temptable pool not enabled"
-regex3="# returns            : ([0-9]+)"
-regex4="# borrows            : ([0-9]+)"
-
-if [[ $tempdata2 =~ $regex2 ]]; then
-  echo "temptable pool is disabled, check skipped"
-else
-  if [[ $tempdata2 =~ $regex3 ]]; then
+  if [[ $tempdata1 =~ $regex1 ]]; then
     num1="${BASH_REMATCH[1]}"
 
     if [[ -n $num1 ]]; then
-      if [[ $tempdata2 =~ $regex4 ]]; then
-        num2="${BASH_REMATCH[1]}"
+      num2="${BASH_REMATCH[2]}"
 
-        if [[ -n $num2 ]]; then
-          if [[ $num1 -ne $num2 ]]; then
-            echo "temptable pool return count $num1 does not match temptable pool borrow count $num2"
-            echo "Failed."
-            exit 1
-          fi
-        else
-          echo "missing temptable pool borrow count"
+      if [[ -n $num2 ]]; then
+        if [[ $num1 -ne 0 ]]; then
+          echo "overall temptable count is not zero"
           echo "Failed."
           exit 1
         fi
+        if [[ $num2 -ne 0 ]]; then
+          echo "SQL temptable count is not zero"
+          echo "Failed."
+          exit 1
+        fi
+      else
+        echo "missing SQL temptable count"
+        echo "Failed."
+        exit 1
       fi
     else
-      echo "missing temptable pool return count"
+      echo "missing overall temptable count"
       echo "Failed."
       exit 1
     fi
   fi
-fi
+
+  tempdata2=$(cat temptable2_${node}.out)
+  regex2="Temptable pool not enabled"
+  regex3="# returns            : ([0-9]+)"
+  regex4="# borrows            : ([0-9]+)"
+
+  if [[ $tempdata2 =~ $regex2 ]]; then
+    echo "temptable pool is disabled, check skipped"
+  else
+    if [[ $tempdata2 =~ $regex3 ]]; then
+      num1="${BASH_REMATCH[1]}"
+
+      if [[ -n $num1 ]]; then
+        if [[ $tempdata2 =~ $regex4 ]]; then
+          num2="${BASH_REMATCH[1]}"
+
+          if [[ -n $num2 ]]; then
+            if [[ $num1 -ne $num2 ]]; then
+              echo "temptable pool return count $num1 does not match temptable pool borrow count $num2"
+              echo "Failed."
+              exit 1
+            fi
+          else
+            echo "missing temptable pool borrow count"
+            echo "Failed."
+            exit 1
+          fi
+        fi
+      else
+        echo "missing temptable pool return count"
+        echo "Failed."
+        exit 1
+      fi
+    fi
+  fi
+done
 
 echo "Passed."
