Add test case
Signed-off-by: Morgan Douglas <mdouglas47@bloomberg.net>

diff --git a/tests/bulkimport.test/runit b/tests/bulkimport.test/runit
--- a/tests/bulkimport.test/runit
+++ b/tests/bulkimport.test/runit
@@ -1,62 +1,29 @@
 #!/usr/bin/env bash
 bash -n "$0" | exit 1
 
+source fixtures.sh
 source constants.sh
 source util.sh
 
-function fixture_src_tbl_and_dst_tbl_are_the_same() {
-	local -n _src_tbl="$1" _dst_tbl="$2"
-	_src_tbl=foo _dst_tbl=foo
-	query_src_db "create table $_src_tbl(i int)"
-	query_src_db "insert into $_src_tbl values(1)"
-	query_dst_db "create table $_dst_tbl(i int)"
+function test_flip_flop_import() {
+	(
+		local src_tbl dst_tbl
+		fixture_src_tbl_and_dst_tbl_are_the_same src_tbl dst_tbl
+		trap "query_src_db 'drop table $src_tbl'; query_dst_db 'drop table $dst_tbl'" EXIT
+
+		# When
+		query_dst_db "import $src_tbl from $SRC_DBNAME to $dst_tbl" && \
+		query_dst_db "insert into $dst_tbl select * from $dst_tbl" && \
+		query_src_db "import $dst_tbl from $DST_DBNAME to $src_tbl" && \
+		query_src_db "insert into $src_tbl select * from $src_tbl" && \
+		query_dst_db "import $src_tbl from $SRC_DBNAME to $dst_tbl"
+
+		# Then
+		rc=$? && verify_import $src_tbl $dst_tbl
+	)
 }
 
-function fixture_src_tbl_and_dst_tbl_have_different_schemas() {
-	local -n _src_tbl="$1" _dst_tbl="$2"
-	_src_tbl=foo _dst_tbl=foo
-	query_src_db "create table $_src_tbl(i int)"
-	query_src_db "insert into $_src_tbl values(1)"
-	query_dst_db "create table $_dst_tbl(i int, j int)"
-}
-
-function fixture_src_tbl_and_dst_tbl_have_different_names() {
-	local -n _src_tbl="$1" _dst_tbl="$2"
-	_src_tbl=foo _dst_tbl=bar
-	query_src_db "create table $_src_tbl(i int)"
-	query_src_db "insert into $_src_tbl values(1)"
-	query_dst_db "create table $_dst_tbl(b blob)"
-}
-
-function fixture_src_tbl_has_noblob_dst_tbl_has_blob() {
-	local -n _src_tbl="$1" _dst_tbl="$2"
-	_src_tbl=foo _dst_tbl=foo
-	query_src_db "create table $_src_tbl(i int)"
-	query_src_db "insert into $_src_tbl values(1)"
-	query_dst_db "create table $_dst_tbl(b blob)"
-}
-
-function fixture_src_tbl_has_blob_dst_tbl_has_no_blob() {
-	local -n _src_tbl="$1" _dst_tbl="$2"
-	_src_tbl=foo _dst_tbl=foo
-	query_src_db "create table $_src_tbl(b blob)"
-	query_src_db "insert into $_src_tbl values(x'f00f')"
-	query_dst_db "create table $_dst_tbl(i int)"
-}
-
-function fixture_src_tbl_was_schema_changed() {
-	local -n _src_tbl="$1" _dst_tbl="$2"
-	_src_tbl=foo _dst_tbl=foo
-	query_src_db "create table $_src_tbl(i int)"
-	query_src_db "insert into $_src_tbl values(1)"
-	query_src_db "alter table $_src_tbl add column j int"
-	query_src_db "insert into $_src_tbl values(2, 3)"
-	query_src_db "alter table $_src_tbl add column b blob"
-	query_src_db "insert into $_src_tbl values(4, 5, x'f00f')"
-	query_dst_db "create table $_dst_tbl(i int)"
-}
-
-function run_test() {
+function run_basic_test() {
 	(
 		# Given
 		local src_tbl dst_tbl
@@ -71,13 +38,27 @@ function run_test() {
 	)
 }
 
-FIXTURES=$(compgen -A function | grep -oh "fixture_\w*")
-
-function main() {
+function test_basic() {
 	for fixture in $FIXTURES;
 	do
-		run_test $fixture
-		failexit $? "Failed to run test with $fixture"
+		run_basic_test $fixture
+		rc=$?
+
+		if (( rc != 0 ));
+		then
+			echo "Failed $FUNCNAME with $fixture"
+			return $rc
+		fi
+	done
+}
+
+TESTS=$(compgen -A function | grep -oh "test_\w*")
+
+function main() {
+	for testcase in $TESTS;
+	do
+		$testcase
+		failexit $? "Failed $testcase"
 	done
 }
 
