Make bulk import run as ddl
Signed-off-by: mdouglas47 <mdouglas47@bloomberg.net>

diff --git a/tests/bulkimport.test/runit b/tests/bulkimport.test/runit
--- a/tests/bulkimport.test/runit
+++ b/tests/bulkimport.test/runit
@@ -60,43 +60,41 @@ function test_import_many_tables_over_table() {
 function test_multiple_imports_at_once() {
 	(
 		# Given
-		local src_tbl=foo dst_tbl=foo n_simultaneous_imports=8 pids=() rc=0
+		local src_tbl=foo dst_tbl=foo n_simultaneous_imports=8 rc=0
 		fixture_src_tbl_and_dst_tbl_have_same_schema $src_tbl $dst_tbl > /dev/null
 		trap "query_src_db 'drop table $src_tbl'; query_dst_db 'drop table $dst_tbl'" EXIT
 
 		# When
-		for i in $(seq $n_simultaneous_imports); do
-			query_dst_db "replace table $dst_tbl with LOCAL_$SRC_DBNAME.$src_tbl" >/dev/null &
-			pids[${i}]=$!
-		done
-
-		for pid in ${pids[@]}; do
-			wait $pid || rc=1
-		done
+		query_dst_db "replace table $dst_tbl with LOCAL_$SRC_DBNAME.$src_tbl" >/dev/null &
+		local -r pid=$!
+		query_dst_db "replace table $dst_tbl with LOCAL_$SRC_DBNAME.$src_tbl" >/dev/null
+		rc_second_import=$?
+		wait $pid
+		rc_first_import=$?
 
 		# Then
-		(( rc == 0 )) && verify_eq $src_tbl $dst_tbl
+		# Whichever import that starts first should fail and the other should succeed.
+		(( (rc_first_import+rc_second_import) == 1 )) && verify_eq $src_tbl $dst_tbl
 	)
 }
 
 function test_mutual_simultaneous_import() {
 	(
 		# Given
-		local src_tbl=foo dst_tbl=foo n_mutual_imports=8 pids=() rc=0
+		local src_tbl=foo dst_tbl=foo n_mutual_imports=8 rc=0
 		fixture_src_tbl_and_dst_tbl_have_same_schema $src_tbl $dst_tbl > /dev/null
 		trap "query_src_db 'drop table $src_tbl'; query_dst_db 'drop table $dst_tbl'" EXIT
 
 		# When
 		for i in $(seq 1 2 $n_mutual_imports); do
 			query_dst_db "replace table $dst_tbl with LOCAL_$SRC_DBNAME.$src_tbl" >/dev/null &
-			pids[${i}]=$!
+			local pid_dst=$!
 
 			query_src_db "replace table $src_tbl with LOCAL_$DST_DBNAME.$dst_tbl" >/dev/null &
-			pids[$((i+1))]=$!
-		done
+			local pid_src=$!
 
-		for pid in ${pids[@]}; do
-			wait $pid || rc=1
+			wait $pid_dst || rc=1
+			wait $pid_src || rc=1
 		done
 
 		# Then
@@ -189,6 +187,34 @@ function test_import_table_with_fk_constraints() {
 	)
 }
 
+function test_multiple_imports_in_failed_transaction() {
+	(
+		# Given
+		local src_tbl_1=foo src_tbl_2=bar src_tbl_3=baz dst_tbl_1=corge dst_tbl_2=qux rc=0
+		fixture_src_tbl_and_dst_tbl_have_same_schema $src_tbl_1 $dst_tbl_1 > /dev/null
+		query_src_db "create table $src_tbl_2(i int unique)"
+		query_src_db "insert into $src_tbl_2 values(1)"
+		query_src_db "create table $src_tbl_3(i int, foreign key(i) references $src_tbl_2(i))"
+		query_dst_db "create table $dst_tbl_2(i int unique)"
+		trap "query_src_db 'drop table $src_tbl_1';
+			query_src_db 'drop table $src_tbl_3';
+			query_src_db 'drop table $src_tbl_2';
+			query_dst_db 'drop table $dst_tbl_1';
+			query_dst_db 'drop table $dst_tbl_2'" EXIT
+
+		# When
+			# Txn should fail because second import runs against constrained table.
+query_dst_db - >/dev/null <<EOF
+begin
+replace table $dst_tbl_1 with LOCAL_$SRC_DBNAME.$src_tbl_1
+replace table $dst_tbl_2 with LOCAL_$SRC_DBNAME.$src_tbl_3
+commit
+EOF
+		# Then
+		(( $? != 0 )) && ! verify_eq $src_tbl_1 $dst_tbl_1 && ! verify_eq $src_tbl_2 $dst_tbl_3
+	)
+}
+
 function test_multiple_imports_in_transaction() {
 	(
 		# Given
@@ -232,7 +258,26 @@ function test_unsupported_version() {
 	)
 }
 
-function test_tunable() {
+function test_protobuf_tunable() {
+	(
+		# Given
+		local src_tbl=foo dst_tbl=bar rc=0
+		fixture_src_tbl_and_dst_tbl_have_same_schema $src_tbl $dst_tbl > /dev/null
+		set_dst_tunable "sc_protobuf 0"
+
+		trap "set_dst_tunable 'sc_protobuf 1';
+			query_src_db 'drop table $src_tbl';
+			query_dst_db 'drop table $dst_tbl'" EXIT
+
+		# When
+		query_dst_db "replace table $dst_tbl with LOCAL_$SRC_DBNAME.$src_tbl"
+
+		# Then
+		(( $? != 0 ))
+	)
+}
+
+function test_feature_tunable() {
 	(
 		# Given
 		local src_tbl=foo dst_tbl=bar rc=0
