The test is working now.

diff --git a/tests/halt_processor_tds.test/runit b/tests/halt_processor_tds.test/runit
--- a/tests/halt_processor_tds.test/runit
+++ b/tests/halt_processor_tds.test/runit
@@ -7,19 +7,20 @@ needcluster=1
 db=$1
 
 # insert metrics
-insert_granularity=10000
-insert_count=10
-insert_loops=10
+insert_granularity=1000
+insert_count=5
 insert_sleep=.5
 
 # update metrics
-update_granularity=10000
-update_count=10
-update_loops=10
+update_granularity=1000
+update_count=5
 update_sleep=.5
 
 # number of master bounces
-master_bounces=20
+master_bounces=5
+
+# length of processor thread poll
+processor_thd_polltime_ms=3000
 
 # 
 stop_file=./testcase.done
@@ -36,15 +37,14 @@ fi
 
 function createtables
 {
-    [[ "$debug" == 1 ]] && set -x
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
     cdb2sql ${CDB2_OPTIONS} $db $stage "create table t1 {schema{int id int val null=yes} keys{ dup \"id\" = id }}" >/dev/null 2>&1
 }
 
 function update_records_loop
 {
-    [[ "$debug" == 1 ]] && set -x
-    iters=$1
-    sleeptime=$2
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
+    sleeptime=$1
 
     while [[ ! -f $stop_file ]]; do
         cdb2sql ${CDB2_OPTIONS} $db $stage "update t1 set id = 1 where 1 limit $update_granularity"
@@ -54,7 +54,7 @@ function update_records_loop
 
 function insert_records_loop
 {
-    [[ "$debug" == 1 ]] && set -x
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
     fname=$1
     sleeptime=$2
 
@@ -64,9 +64,32 @@ function insert_records_loop
     done
 }
 
+function block_until_connected
+{
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
+    timeout=$1
+    starttime=$(date +%s)
+    err=1
+    while [ $err -ne 0 ] ; do 
+        err=0
+        for node in $CLUSTER ; do
+            cdb2sql ${CDB2_OPTIONS} $db default --host $node "select 1"
+            if [[ $? != 0 ]]; then 
+                err=1
+            fi
+        done
+        sleep 1
+        nowtime=$(date +%s)
+        if (( nowtime - starttime >= timeout )) ; then
+            echo "${FUNCNAME[0]} timed out"
+            return 1
+        fi
+    done
+}
+
 function bounce_master
 {
-    [[ "$debug" == 1 ]] && set -x
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
     master=`cdb2sql -tabs ${CDB2_OPTIONS} $db default 'exec procedure sys.cmd.send("bdb cluster")' | grep MASTER | cut -f1 -d":" | tr -d '[:space:]' `
     PARAMS="$db --no-global-lrl"
     CMD="source ${TESTDIR}/replicant_vars ; ${COMDB2_EXE} ${PARAMS} --lrl $DBDIR/${db}.lrl -pidfile ${TMPDIR}/${db}.pid"
@@ -86,7 +109,7 @@ function bounce_master
 
 function runtest
 {
-    [[ "$debug" == 1 ]] && set -x
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
 
     fname=insert.sql
 
@@ -102,10 +125,13 @@ function runtest
 
     rm $stop_file
 
+    pidlist=""
+
     # Insert a bunch of records
     i=0
     while [[ $i -lt $insert_count ]]; do
         insert_records_loop $fname $insert_sleep &
+        pidlist="$pidlist $!"
         let i=i+1
     done
 
@@ -113,22 +139,24 @@ function runtest
     i=0
     while [[ $i -lt $update_count ]]; do
         update_records_loop $update_sleep &
+        pidlist="$pidlist $!"
         let i=i+1
     done
 
     # Poll for 10 seconds in the processor thread 
     for node in $CLUSTER; do
-        cdb2sql ${CDB2_OPTIONS} $db default --host $node "PUT TUNABLE processor_thd_poll 10000"
+        cdb2sql ${CDB2_OPTIONS} $db default --host $node "PUT TUNABLE processor_thd_poll $processor_thd_polltime_ms"
     done
 
     let j=0
 
     while [[ $j -lt $master_bounces ]] ; do 
 
+        block_until_connected 20
         bounce_master
 
         for node in $CLUSTER; do
-            cdb2sql ${CDB2_OPTIONS} $db default --host $node "PUT TUNABLE processor_thd_poll 10000"
+            cdb2sql ${CDB2_OPTIONS} $db default --host $node "PUT TUNABLE processor_thd_poll $processor_thd_polltime_ms"
         done
 
         sleep 1
@@ -137,7 +165,7 @@ function runtest
 
     touch $stop_file
 
-    wait
+    wait -n $pidlist
     rm $fname
 
     err=0
@@ -160,7 +188,7 @@ function runtest
 
 function exitdatabase
 {
-    [[ "$debug" == 1 ]] && set -x
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
 
     if [[ -n "$CLUSTER" ]]; then
         for node in $CLUSTER; do
@@ -173,13 +201,19 @@ function exitdatabase
 
 function checkforcorruption
 {
+    [[ "$debug" == 1 ]] && echo "START ${FUNCNAME[0]}" && set -x
     egrep -i "Log sequence error" $TESTDIR/logs/*db
     if [[ $? == 0 ]]; then
-        echo "CORRUPTED DATABASE, TEST FAILED"
+        echo "CORRUPTED DATABASE, LOG SEQUENCE ERROR.  TEST FAILED"
+        exit 1
+    fi
+
+    egrep -i "Recovery function" $TESTDIR/logs/*db | egrep -i failed
+    if [[ $? == 0 ]]; then
+        echo "RECOVERY FUNCTION FAILED.  TEST FAILED"
         exit 1
     fi
 }
-
 
 createtables
 runtest
