{174625959} sqlite: Build with SQLITE_64BIT_STATS
Also,
* Update stat4dump to print u64.
* Enable stat4dump in datacopy test.

Signed-off-by: Akshat Sikarwar <asikarwar1@bloomberg.net>

diff --git a/tests/datacopy.test/runit b/tests/datacopy.test/runit
--- a/tests/datacopy.test/runit
+++ b/tests/datacopy.test/runit
@@ -2,8 +2,8 @@
 bash -n "$0" | exit 1
 
 DB="$1"
-cdb2sql -s ${CDB2_OPTIONS} $DB default "exec procedure sys.cmd.send('ndebg 500')"
-cdb2sql -s ${CDB2_OPTIONS} $DB default "exec procedure sys.cmd.send('debg 500')"
+#cdb2sql -s ${CDB2_OPTIONS} $DB default "exec procedure sys.cmd.send('ndebg 500')"
+#cdb2sql -s ${CDB2_OPTIONS} $DB default "exec procedure sys.cmd.send('debg 500')"
 cdb2sql -s ${CDB2_OPTIONS} $DB default "drop table t" &> /dev/null
 cdb2sql ${CDB2_OPTIONS} $DB default 'create table t {
 schema
@@ -22,22 +22,14 @@ keys
 }
 }'
 
-i=1
-while [[ $i -lt 25 ]]; do
-	j=$(( 24 - $i ))
-	echo "insert into t(i, j) values(1, $j);"
-	i=$(( $i + 1 ))
-done | cdb2sql -s ${CDB2_OPTIONS} $DB default - > /dev/null
-
+cdb2sql ${CDB2_OPTIONS} $DB default "insert into t select 1, 24 - value from generate_series(1, 24)"
 cdb2sql ${CDB2_OPTIONS} $DB default 'exec procedure sys.cmd.analyze("","100")'
-#AZ: kills sql thread on server: cdb2sql ${CDB2_OPTIONS} $DB default 'exec procedure sys.cmd.send("stat4dump")'
-#comdb2sc $DB send stat4dump 2>&1 > sqlite_stat4.output
-
-#diff sqlite_stat4.output sqlite_stat4.expected
-#if [[ $? -ne 0 ]] ; then
-#    echo "Failed"
-#    exit $?
-#fi
+cdb2sql -tabs ${CDB2_OPTIONS} $DB default 'exec procedure sys.cmd.send("stat4dump")' > sqlite_stat4.output
+diff sqlite_stat4.output sqlite_stat4.expected
+if [[ $? -ne 0 ]] ; then
+    echo "Failed"
+    exit $?
+fi
 
 # POPULATE STAT4 ROWS ORDERED RANDOMLY
 # IN MEMORY REPRESENTATION SHOULD STILL BE SORTED
@@ -46,13 +38,13 @@ while [[ $i -lt 100 ]]; do
     set -e
 	cdb2sql -s ${CDB2_OPTIONS} $DB default "delete from sqlite_stat4 where 1" > /dev/null
 	cat sqlite_stat4.sql | perl -MList::Util=shuffle -e 'print shuffle(<STDIN>);' | cdb2sql -s ${CDB2_OPTIONS} $DB default - > /dev/null
-#comdb2sc $DB send stat4dump 2>&1 > sqlite_stat4.output
-#	diff sqlite_stat4.output sqlite_stat4.expected
-#	if [[ $? -ne 0 ]] ; then
-#        echo "Failed"
-#        exit $?
-#    fi
-	i=$(( $i + 1 ))
+    cdb2sql -tabs ${CDB2_OPTIONS} $DB default 'exec procedure sys.cmd.send("stat4dump")' > sqlite_stat4.output.$i
+    diff sqlite_stat4.output.$i sqlite_stat4.expected
+    if [[ $? -ne 0 ]] ; then
+        echo "Failed - $i"
+        exit $?
+    fi
+    i=$(( $i + 1 ))
 done
 
 set -e
