Cut-1 of fix - but still not working

diff --git a/tests/random_osql_replay.test/runit b/tests/random_osql_replay.test/runit
--- a/tests/random_osql_replay.test/runit
+++ b/tests/random_osql_replay.test/runit
@@ -3,12 +3,29 @@
 bash -n "$0" | exit 1
 
 set -x
+maxloop=10000
 
-# Create table
 cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "create table t1 ( a int primary key )"
+cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "truncate t1"
 
-for x in $(seq 1 100000) ; do 
+for x in $(seq 1 $maxloop) ; do 
     cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "insert into t1 values ($x)"
+    if [[ $? != 0 ]]; then
+        echo "Testcase failed"
+        exit 1
+    fi
+done
+
+for x in $(seq 1 $maxloop) ; do 
+    cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "update t1 set a = a + $maxloop where a = $x"
+    if [[ $? != 0 ]]; then
+        echo "Testcase failed"
+        exit 1
+    fi
+done
+
+for x in $(seq 1 $maxloop) ; do 
+    cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "delete from t1 where a = $x + $maxloop"
     if [[ $? != 0 ]]; then
         echo "Testcase failed"
         exit 1
