Add fastinit loop

diff --git a/tests/random_osql_replay.test/runit b/tests/random_osql_replay.test/runit
--- a/tests/random_osql_replay.test/runit
+++ b/tests/random_osql_replay.test/runit
@@ -9,6 +9,20 @@ cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "create table t1 ( a int primary key )
 cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "truncate t1"
 
 for x in $(seq 1 $maxloop) ; do 
+    cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "truncate t1"
+    if [[ $? != 0 ]]; then
+        echo "Testcase failed"
+        exit 1
+    fi
+
+    cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "insert into t1 values ($x)"
+    if [[ $? != 0 ]]; then
+        echo "Testcase failed"
+        exit 1
+    fi
+done
+
+for x in $(seq 1 $maxloop) ; do 
     cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "insert into t1 values ($x)"
     if [[ $? != 0 ]]; then
         echo "Testcase failed"
@@ -31,6 +45,7 @@ for x in $(seq 1 $maxloop) ; do
         exit 1
     fi
 done
+
 
 echo "Success"
 exit 0
