Add cdb2api_cfg test
Signed-off-by: Michael Ponomarenko <mponomarenko@bloomberg.net>

diff --git a/tests/api_tst.test/runit b/tests/api_tst.test/runit
--- a/tests/api_tst.test/runit
+++ b/tests/api_tst.test/runit
@@ -66,4 +66,29 @@ ${TESTSBUILDDIR}/cdb2api_unread_data ${DBNAME}
 sed -i '/comdb2_feature:discard_unread_socket_data=on/d' "${cfg}"
 echo 'cdb2api_unread_data - pass'
 
+comdb2db_cfg=api_tst_comdb2db.cfg
+dbname_cfg=api_tst_${db}.cfg
+for global_tier in local dev integration beta prod proxy; do
+    echo "comdb2_config:default_type=${global_tier}" > ${comdb2db_cfg}
+    for db_tier in local dev integration beta prod proxy; do
+        cat > ${dbname_cfg} <<-EOF
+                comdb2_config:default_type=${db_tier}
+                comdb2_config:api_call_timeout=1
+                comdb2_config:comdb2db_timeout=1
+                comdb2_config:connect_timeout=1
+                comdb2_config:socket_timeout=1
+                comdb2_feature:use_bmsd=0
+EOF
+        exp="${global_tier}:${db_tier}"
+        res=$(${TESTSBUILDDIR}/cdb2api_cfg ${db} default ${comdb2db_cfg} ${dbname_cfg} 2> /dev/null)
+        if [[ "${res}" !=  "${exp}" ]] ; then
+            echo >&2 "cfg expected:${exp} result:${res} - fail"
+            exit 1
+        else
+            echo "${res} ok"
+        fi
+    done
+done
+echo "cfg - pass"
+
 exit 0
